---
- name: apt clean
  become: yes
  apt:
    autoclean: yes

- name: apt install
  become: yes
  apt:
    update_cache: yes
    pkg:
      - bash
      - rsync
      - psmisc
      - procps
      - unattended-upgrades
      - fail2ban
      - postfix
      - less
      - vim

- name: apt remove
  become: yes
  apt:
    state: absent
    pkg:
      - nano

- name: apt purge
  become: yes
  apt:
    autoremove: yes
