---
- name: apt clean
  become: yes
  apt:
    autoclean: yes

- name: apt install
  become: yes
  apt:
    update_cache: yes
    pkg:
      - bash
      - rsync
      - psmisc
      - procps
      - unattended-upgrades
      - fail2ban
      - postfix
      - sudo
      - less
      - vim

- name: apt remove
  become: yes
  apt:
    state: absent
    pkg:
      - nano

- name: apt purge
  become: yes
  apt:
    autoremove: yes

- name: set hostname
  become: yes
  hostname:
    name: "{{ ansible_host }}"

- name: root home dir
  become: yes
  file:
    state: directory
    path: /root
    owner: root
    group: root
    mode: '0750'

- name: uws group
  become: yes
  group:
    state: present
    name: uws
    gid: 1500

- name: uws user
  become: yes
  user:
    state: present
    name: uws
    uid: 1500
    append: no
    comment: uws
    create_home: yes
    group: uws
    groups: sudo
    home: /home/uws
    shell: /bin/bash

- name: uws home dir
  become: yes
  file:
    state: directory
    path: /home/uws
    owner: uws
    group: uws
    mode: '0750'
