---
- name: apt install
  become: yes
  apt:
    update_cache: yes
    pkg:
      - bash
      - awscli
      - rsync
      - psmisc
      - procps
      - unattended-upgrades
      - fail2ban
      - postfix
