---
#
# host
#
- name: hostname
  become: yes
  hostname:
    name: "{{ ansible_host }}"
  tags:
    - host

- name: timezone
  become: yes
  timezone:
    name: UTC
  tags:
    - host
#
# apt
#
- name: apt sources
  become: yes
  template:
    src: apt/sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
  when: apt_sources_update
  tags:
    - apt

- name: apt clean
  become: yes
  apt:
    autoclean: yes
  tags:
    - apt

- name: apt update
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: apt install
  become: yes
  apt:
    pkg:
      - bash
      - python3
      - rsync
      - psmisc
      - procps
      - unattended-upgrades
      - needrestart
      - postfix
      - cron
      - sudo
      - ca-certificates
      - ssl-cert
      - bsd-mailx
      - less
      - vim
      - xz-utils
      - acl
  tags:
    - apt

- name: apt remove
  become: yes
  apt:
    state: absent
    autoremove: yes
    purge: yes
    pkg:
      - nano
  tags:
    - apt

- name: apt purge
  become: yes
  apt:
    autoremove: yes
    purge: yes
  tags:
    - apt
#
# root
#
- name: root home dir
  become: yes
  file:
    state: directory
    path: /root
    owner: root
    group: root
    mode: '0750'
  tags:
    - root
#
# admin
#
- name: "{{ ansible_user }} home dir"
  become: yes
  file:
    state: directory
    path: "~{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0750'
  tags:
    - admin

- name: "{{ ansible_user }} bin dir"
  become: yes
  file:
    state: directory
    path: "~{{ ansible_user }}/bin"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0750'
  tags:
    - admin
#
# uws
#
- name: uws group
  become: yes
  group:
    state: present
    name: uws
    gid: 1500
  tags:
    - uws

- name: uws user
  become: yes
  user:
    state: present
    name: uws
    uid: 1500
    append: no
    comment: uws
    create_home: yes
    group: uws
    home: /home/uws
    shell: /bin/bash
  tags:
    - uws

- name: uws user groups
  become: yes
  user:
    name: uws
    append: yes
    groups: "{{ ansible_user }}"
  tags:
    - uws

- name: uws home dir
  become: yes
  file:
    state: directory
    path: /home/uws
    owner: uws
    group: uws
    mode: '0750'
  tags:
    - uws
#
# sudo
#
- name: uws sudoers
  become: yes
  copy:
    force: yes
    owner: root
    group: root
    mode: '0440'
    dest: /etc/sudoers.d/99zzz-uws
    content: "uws ALL = (ALL) NOPASSWD:ALL\n"
  tags:
    - uws
    - sudo
#
# ssh
#
- name: uws ssh authorized keys
  become: yes
  authorized_key:
    state: present
    user: uws
    comment: "{{ item }}@github.com"
    key: https://github.com/{{ item }}.keys
    manage_dir: yes
    exclusive: yes
  loop: "{{ uws_authorized_key }}"
  tags:
    - uws
    - ssh
#
# sshd
#
- name: sshd config
  become: yes
  template:
    src: ssh/sshd_config
    dest: /etc/ssh/sshd_config.d/uws.conf
    owner: root
    group: root
    mode: '0640'
    validate: sshd -t -f %s
  register: sshd_config
  notify:
    - restart sshd
  tags:
    - sshd
