---
#
# apt
#
- name: apt sources
  become: yes
  template:
    src: apt/sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
  tags:
    - apt

- name: apt clean
  become: yes
  apt:
    autoclean: yes
  tags:
    - apt

- name: apt install
  become: yes
  apt:
    update_cache: yes
    pkg:
      - bash
      - rsync
      - psmisc
      - procps
      - unattended-upgrades
      - fail2ban
      - postfix
      - sudo
      - netfilter-persistent
      - iptables-persistent
      - bsd-mailx
      - less
      - vim
  tags:
    - apt

- name: apt remove
  become: yes
  apt:
    state: absent
    pkg:
      - nano
  tags:
    - apt

- name: apt purge
  become: yes
  apt:
    autoremove: yes
  tags:
    - apt
#
# host
#
- name: hostname
  become: yes
  hostname:
    name: "{{ ansible_host }}"
  tags:
    - host
#
# root
#
- name: root home dir
  become: yes
  file:
    state: directory
    path: /root
    owner: root
    group: root
    mode: '0750'
  tags:
    - root
#
# uws
#
- name: uws group
  become: yes
  group:
    state: present
    name: uws
    gid: 1500
  tags:
    - uws

- name: uws user
  become: yes
  user:
    state: present
    name: uws
    uid: 1500
    append: no
    comment: uws
    create_home: yes
    group: uws
    home: /home/uws
    shell: /bin/bash
  tags:
    - uws

- name: uws home dir
  become: yes
  file:
    state: directory
    path: /home/uws
    owner: uws
    group: uws
    mode: '0750'
  tags:
    - uws
#
# sudo
#
- name: uws sudoers
  become: yes
  copy:
    force: yes
    owner: root
    group: root
    mode: '0440'
    dest: /etc/sudoers.d/99zzz-uws
    content: "uws ALL = (ALL) NOPASSWD:ALL\n"
  tags:
    - uws
    - sudo
#
# ssh
#
- name: uws ssh authorized keys
  become: yes
  authorized_key:
    state: present
    user: uws
    comment: "{{ item }}@github.com"
    key: https://github.com/{{ item }}.keys
    manage_dir: yes
    exclusive: yes
  loop: "{{ uws_authorized_key }}"
  tags:
    - uws
    - ssh
#
# iptables
#
- name: iptables rules
  become: yes
  template:
    src: iptables/{{ item }}
    dest: /etc/iptables/{{ item }}
    owner: root
    group: root
    mode: '0640'
  loop:
    - rules.v4
    - rules.v6
  register: iptables_rules
  tags:
    - iptables

- name: iptables reload
  become: yes
  command:
    cmd: service netfilter-persistent reload
    warn: no
  when: iptables_rules.changed
  tags:
    - iptables
