---
#
# host
#
- name: Debian hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ ansible_host }}"
  tags:
    - host

- name: Debian timezone
  become: true
  community.general.timezone:
    name: UTC
  tags:
    - host
#
# apt
#
- name: Debian apt sources
  become: true
  ansible.builtin.template:
    src: apt/sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
  when: apt_sources_update
  tags:
    - apt

- name: Debian apt clean
  become: true
  ansible.builtin.apt:
    autoclean: true
  tags:
    - apt

- name: Debian apt update
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Debian apt install
  become: true
  ansible.builtin.apt:
    pkg:
      - bash
      - python3
      - rsync
      - psmisc
      - procps
      - unattended-upgrades
      - needrestart
      - postfix
      - cron
      - sudo
      - ca-certificates
      - ssl-cert
      - bsd-mailx
      - less
      - vim
      - xz-utils
      - acl
  tags:
    - apt

- name: Debian apt remove
  become: true
  ansible.builtin.apt:
    state: absent
    autoremove: true
    purge: true
    pkg:
      - nano
  tags:
    - apt

- name: Debian apt purge
  become: true
  ansible.builtin.apt:
    autoremove: true
    purge: true
  tags:
    - apt
#
# root
#
- name: Debian root home dir
  become: true
  ansible.builtin.file:
    state: directory
    path: /root
    owner: root
    group: root
    mode: '0750'
  tags:
    - root
#
# admin
#
- name: "Debian home dir {{ ansible_user }}"
  become: true
  ansible.builtin.file:
    state: directory
    path: "~{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0750'
  tags:
    - admin

- name: "Debian bin dir {{ ansible_user }}"
  become: true
  ansible.builtin.file:
    state: directory
    path: "~{{ ansible_user }}/bin"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0750'
  tags:
    - admin
#
# uws
#
- name: Debian uws group
  become: true
  ansible.builtin.group:
    state: present
    name: uws
    gid: 1500
  tags:
    - uws

- name: Debian uws user
  become: true
  ansible.builtin.user:
    state: present
    name: uws
    uid: 1500
    append: false
    comment: uws
    create_home: true
    group: uws
    home: /home/uws
    shell: /bin/bash
  tags:
    - uws

- name: Debian uws user groups
  become: true
  ansible.builtin.user:
    name: uws
    append: true
    groups: "{{ ansible_user }}"
  tags:
    - uws

- name: Debian uws home dir
  become: true
  ansible.builtin.file:
    state: directory
    path: /home/uws
    owner: uws
    group: uws
    mode: '0750'
  tags:
    - uws
#
# sudo
#
- name: Debian uws sudoers
  become: true
  ansible.builtin.copy:
    force: true
    owner: root
    group: root
    mode: '0440'
    dest: /etc/sudoers.d/99zzz-uws
    content: "uws ALL = (ALL) NOPASSWD:ALL\n"
  tags:
    - uws
    - sudo
#
# ssh
#
- name: Debian uws ssh authorized keys
  become: true
  ansible.posix.authorized_key:
    state: present
    user: uws
    comment: "{{ item }}@github.com"
    key: https://github.com/{{ item }}.keys
    manage_dir: true
    exclusive: true
  loop: "{{ uws_authorized_key }}"
  tags:
    - uws
    - ssh
#
# sshd
#
- name: Debian sshd config
  become: true
  ansible.builtin.template:
    src: ssh/sshd_config
    dest: /etc/ssh/sshd_config.d/uws.conf
    owner: root
    group: root
    mode: '0640'
    validate: sshd -t -f %s
  register: sshd_config
  notify:
    - restart sshd
  tags:
    - sshd
