---
- name: apt clean
  become: yes
  apt:
    autoclean: yes

- name: apt install
  become: yes
  apt:
    update_cache: yes
    pkg:
      - bash
      - rsync
      - psmisc
      - procps
      - unattended-upgrades
      - fail2ban
      - postfix
      - less
      - vim

- name: apt remove
  become: yes
  apt:
    state: absent
    pkg:
      - nano

- name: apt purge
  become: yes
  apt:
    autoremove: yes

- name: set hostname
  become: yes
  hostname:
    name: "{{ ansible_host }}"

- name: root home dir
  become: yes
  file:
    state: directory
    path: /root
    owner: root
    group: root
    mode: '0750'
