---
- name: Nginx apt install
  become: true
  ansible.builtin.apt:
    pkg:
      - nginx
  tags:
    - apt
    - nginx-apt

- name: Nginx index.html
  become: true
  ansible.builtin.template:
    src: www/index.html
    dest: /var/www/html/index.html
    mode: '0644'
    owner: root
    group: root
  tags:
    - nginx

- name: Nginx server config
  become: true
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/conf.d/zzzuws.conf
    mode: '0644'
    owner: root
    group: root
  notify:
    - Nginx reload
  tags:
    - nginx

- name: Nginx default server
  become: true
  ansible.builtin.template:
    src: nginx/default.conf
    dest: /etc/nginx/sites-enabled/default
    mode: '0644'
    owner: root
    group: root
  register: nginx_config
  notify:
    - Nginx reload
  tags:
    - nginx

- name: Nginx reload config
  become: true
  ansible.builtin.service:
    name: nginx
    state: reloaded
  tags:
    - nginx
