---
- name: apt install
  become: yes
  apt:
    pkg:
      - nginx
  tags:
    - apt
    - nginx-apt

- name: index.html
  become: yes
  template:
    src: www/index.html
    dest: /var/www/html/index.html
    mode: '0644'
    owner: root
    group: root
  tags:
    - nginx

- name: server config
  become: yes
  template:
    src: nginx.conf
    dest: /etc/nginx/conf.d/zzzuws.conf
    mode: '0644'
    owner: root
    group: root
  register: nginx_config
  tags:
    - nginx

- name: default server
  become: yes
  template:
    src: nginx/default.conf
    dest: /etc/nginx/sites-enabled/default
    mode: '0644'
    owner: root
    group: root
  register: nginx_default_server
  tags:
    - nginx

- name: service reload
  become: yes
  service:
    name: nginx
    state: reloaded
  when: nginx_config.changed or nginx_default_server.changed
  tags:
    - nginx
