---
- name: apt install
  become: true
  apt:
    pkg:
      - nginx
  tags:
    - apt
    - nginx-apt

- name: index.html
  become: true
  template:
    src: www/index.html
    dest: /var/www/html/index.html
    mode: '0644'
    owner: root
    group: root
  tags:
    - nginx

- name: server config
  become: true
  template:
    src: nginx.conf
    dest: /etc/nginx/conf.d/zzzuws.conf
    mode: '0644'
    owner: root
    group: root
  notify:
    - reload nginx
  tags:
    - nginx

- name: default server
  become: true
  template:
    src: nginx/default.conf
    dest: /etc/nginx/sites-enabled/default
    mode: '0644'
    owner: root
    group: root
  register: nginx_config
  notify:
    - reload nginx
  tags:
    - nginx

- name: reload config
  become: true
  service:
    name: nginx
    state: reloaded
  when: nginx_config is changed
  tags:
    - nginx
