---
- name: apt install
  become: yes
  apt:
    pkg:
      - nginx
  tags:
    - apt
    - nginx-apt

- name: index.html
  become: yes
  template:
    src: www/index.html
    dest: /var/www/html/index.html
    mode: '0644'
    owner: root
    group: root
  tags:
    - nginx
