---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: offline-page
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: offline-page
  replicas: ${APP_REPLICAS}
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: offline-page
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - image: 789470191893.dkr.ecr.${AWS_REGION}.amazonaws.com/uws:offline-page-${APP_VERSION}
          imagePullPolicy: IfNotPresent
          name: offline-page
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: rundir
              mountPath: "/run"
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              cpu: 10m
              memory: 100Mi
          readinessProbe:
            exec:
              command:
                - cat
                - /usr/local/etc/lighttpd.conf
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 3
      volumes:
        - name: rundir
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: offline-page
spec:
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: offline-page
