version: '3.7'

services:
  meteor-worker:
    image: uws/api
    networks:
      - mworker-net
    volumes:
      - mworkerapp:/home/uws/meteor/app:ro
    secrets:
      - source: mworker-env
        target: /home/uws/meteor/app.env
    deploy:
      replicas: 10
      #~ placement:
        #~ max_replicas_per_node: 10
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

networks:
  mworker-net: {}
