---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: nlp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nlp-api
  replicas: 15
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nlp-api
    spec:
      containers:
        - image: 789470191893.dkr.ecr.${AWS_REGION}.amazonaws.com/uws:nlp-api-${APP_VERSION}
          imagePullPolicy: IfNotPresent
          name: nlp-api
          ports:
            - containerPort: 5000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 3000
            runAsGroup: 1001
          env:
            - name: NER_URL
              value: "http://ner.nlp:5100"
            - name: SENTIMENT_URL
              value: "http://sentiment.nlp:5200"
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              cpu: 10m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: nlp
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app.kubernetes.io/name: nlp-api
