FROM uws/base-2211

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="221116"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh less shellcheck python3 python3-doc python3-mypy \
	python3-coverage libjs-jquery libjs-jquery-isonscreen \
	libjs-jquery-throttle-debounce libjs-jquery-tablesorter

USER uws:uws
WORKDIR /home/uws

ENV USER uws
ENV HOME /home/uws

RUN /usr/bin/python3 --version

WORKDIR /opt/uws
CMD /usr/local/bin/uws-login.sh
