---
- name: mailname
  become: yes
  copy:
    force: yes
    owner: root
    group: root
    mode: '0644'
    dest: /etc/mailname
    content: "{{ postconf_mailname or ansible_host }}\n"
  tags:
    - postconf

- name: root aliases
  become: yes
  lineinfile:
    state: present
    owner: root
    group: root
    mode: '0644'
    path: /etc/aliases
    regexp: "^{{ item }}:"
    line: "{{ item }}: root"
  loop:
    - postmaster
    - admin
    - uws
    - www-data
    - munin
  register: postconf_aliases
  tags:
    - postconf

- name: newaliases
  become: yes
  command: newaliases
  when: postconf_aliases.changed
  tags:
    - postconf

- name: main.cf
  become: yes
  template:
    src: postfix/main.cf
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
    backup: yes
  register: postconf_main
  tags:
    - postconf

- name: service restart
  become: yes
  service:
    state: restarted
    name: postfix
  when: postconf_aliases.changed or postconf_main.changed
  tags:
    - postconf
