---
- name: Postfix mailname
  become: true
  ansible.builtin.copy:
    force: true
    owner: root
    group: root
    mode: '0644'
    dest: /etc/mailname
    content: "{{ postconf_mailname or ansible_host }}\n"
  tags:
    - postconf

- name: Postfix aliases
  become: true
  ansible.builtin.lineinfile:
    state: present
    owner: root
    group: root
    mode: '0644'
    path: /etc/aliases
    regexp: "^{{ item }}:"
    line: "{{ item }}: root"
  loop:
    - postmaster
    - admin
    - uws
    - www-data
    - munin
    - monit
  notify:
    - Postfix newaliases
  tags:
    - postconf

- name: Postfix munin-alert alias
  become: true
  ansible.builtin.lineinfile:
    state: present
    path: /etc/aliases
    regexp: "^munin-alert:"
    line: "munin-alert: munin-alert@{{ uws_domain }}"
  notify:
    - Postfix newaliases
  tags:
    - postconf

- name: Postfix root alias
  become: true
  ansible.builtin.lineinfile:
    state: present
    path: /etc/aliases
    regexp: "^root:"
    line: "root: root@{{ uws_domain }}"
  notify:
    - Postfix newaliases
  tags:
    - postconf

- name: Postfix smtps CA files
  become: true
  when: not postconf_smtps_server
  tags:
    - postconf
  block:
    - name: Postfix smtps CA
      ansible.builtin.copy:
        src: ~/ca/{{ uwsca_smtps }}/rootCA.pem
        dest: /etc/ssl/certs/uws-smtps-CA.pem
        owner: root
        group: root
        mode: '0644'
      notify:
        - Postfix restart
    - name: Postfix smtps client cert
      ansible.builtin.copy:
        src: ~/ca/{{ uwsca_smtps }}/client/{{ uwsca_smtps_client }}.pem
        dest: /etc/ssl/certs/uws-smtps.pem
        owner: root
        group: root
        mode: '0644'
      notify:
        - Postfix restart
    - name: Postfix smtps client key
      ansible.builtin.copy:
        src: ~/ca/{{ uwsca_smtps }}/client/{{ uwsca_smtps_client }}.key
        dest: /etc/ssl/private/uws-smtps.key
        owner: root
        group: ssl-cert
        mode: '0640'
      notify:
        - Postfix restart

- name: Postfix main.cf
  become: true
  ansible.builtin.template:
    src: postfix/main.cf
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Postfix restart
  tags:
    - postconf
