---
- name: mailname
  become: yes
  copy:
    force: yes
    owner: root
    group: root
    mode: '0644'
    dest: /etc/mailname
    content: "{{ postconf_mailname or ansible_host }}\n"
  tags:
    - postconf

- name: aliases
  become: yes
  lineinfile:
    state: present
    owner: root
    group: root
    mode: '0644'
    path: /etc/aliases
    regexp: "^{{ item }}:"
    line: "{{ item }}: root"
  loop:
    - postmaster
    - admin
    - uws
    - www-data
    - munin
  notify:
    - newaliases
  tags:
    - postconf

- name: root alias
  become: yes
  lineinfile:
    state: present
    path: /etc/aliases
    regexp: "^root:"
    line: "root: root@{{ uws_domain }}"
  notify:
    - newaliases
  tags:
    - postconf

- name: smtps CA files
  become: yes
  block:
    - name: smtps CA
      copy:
        src: ~/ca/{{ uwsca_smtps }}/rootCA.pem
        dest: /etc/ssl/certs/uws-smtps-CA.pem
        owner: root
        group: root
        mode: '0644'
    - name: smtps client cert
      copy:
        src: ~/ca/{{ uwsca_smtps }}/client/{{ uwsca_smtps_client }}.pem
        dest: /etc/ssl/certs/uws-smtps.pem
        owner: root
        group: root
        mode: '0644'
    - name: smtps client key
      copy:
        src: ~/ca/{{ uwsca_smtps }}/client/{{ uwsca_smtps_client }}.key
        dest: /etc/ssl/private/uws-smtps.key
        owner: root
        group: ssl-cert
        mode: '0640'
  when: not postconf_smtps_server
  tags:
    - postconf

- name: main.cf
  become: yes
  template:
    src: postfix/main.cf
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart postfix
  tags:
    - postconf
