---
apiVersion: v1
kind: Service
metadata:
  name: kubeshark-front
spec:
  type: ExternalName
  externalName: kubeshark-front.kubeshark.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: kubeshark-hub
spec:
  type: ExternalName
  externalName: kubeshark-hub.kubeshark.svc.cluster.local
