---
controller:
  autoscaling:
    enabled: false
    #~ minReplicas: 3
    #~ maxReplicas: 11
    #~ targetCPUUtilizationPercentage: 50
    #~ targetMemoryUtilizationPercentage: 50
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
  resources:
    requests:
      cpu: 400m
      memory: 1500Mi
    limits:
      cpu: 400m
      memory: 1500Mi
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
  minAvailable: 1
  replicaCount: 3
