---
- name: rstudio ec2 vm
  hosts: rstudio
  gather_facts: false
  tasks:

    - name: rstudio vpc
      delegate_to: localhost
      ec2_vpc_net:
        name: rstudio-vpc
        state: present
        tags:
          Name: rstudio-vpc
        cidr_block: 172.27.0.0/16
      register: rstudio_vpc

    - name: rstudio subnet
      delegate_to: localhost
      ec2_vpc_subnet:
        state: present
        assign_instances_ipv6: false
        map_public: true
        cidr: 172.27.1.0/24
        vpc_id: "{{ rstudio_vpc.vpc.id }}"
        tags:
          Name: rstudio-subnet
      register: rstudio_subnet

    - name: rstudio security group
      delegate_to: localhost
      ec2_group:
        name: rstudio-sg
        description: rstudio security group
        state: present
        tags:
          Name: rstudio-sg
        vpc_id: "{{ rstudio_vpc.vpc.id }}"
        rules:
          - proto: tcp
            ports:
              - 22
              - 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    - name: rstudio vm create
      delegate_to: localhost
      ec2:
        monitoring: false
        termination_protection: true
        key_name: asbhost-rstudio
        group: rstudio-sg
        ebs_optimized: false
        volumes:
          - device_name: /dev/xvda
            volume_type: gp3
            volume_size: 10
            delete_on_termination: true
            encrypted: true
        image: "{{ debian_ami }}"
        vpc_subnet_id: "{{ rstudio_subnet.subnet.id }}"
        instance_type: "{{ vm_type }}"
        instance_tags:
          Name: "{{ inventory_hostname }}"
        exact_count: 1
        count_tag:
          Name: "{{ inventory_hostname }}"

    - name: rstudio vm running
      delegate_to: localhost
      ec2:
        state: running
        wait: true
        wait_timeout: 600
        instance_tags:
          Name: "{{ inventory_hostname }}"
