---
- name: RStudio ec2 vm teardown
  hosts: rstudio_teardown
  gather_facts: false
  tasks:

    - name: RStudio teardown vm
      delegate_to: localhost
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Name": "{{ vm_tag_name or inventory_hostname }}"
      register: teardown_vm
      tags:
        - dns

    - name: RStudio teardown vm dns record
      delegate_to: localhost
      amazon.aws.route53:
        state: absent
        zone: uws.talkingpts.org
        record: "{{ ansible_host }}"
        value: "{{ teardown_vm.instances.0.public_dns_name or vm_public_dns_name }}"
        ttl: 600
        type: CNAME
      when: teardown_vm.instances
      tags:
        - dns

    - name: RStudio teardown vm stop
      delegate_to: localhost
      amazon.aws.ec2_instance:
        state: stopped
        wait: true
        wait_timeout: 600
        instance_ids: "{{ teardown_vm.instances.0.instance_id }}"
        termination_protection: false
      when: teardown_vm.instances

    - name: RStudio teardown vm terminate
      delegate_to: localhost
      amazon.aws.ec2_instance:
        state: absent
        wait: true
        wait_timeout: 600
        instance_ids: "{{ teardown_vm.instances.0.instance_id }}"
      when: teardown_vm.instances
