---
- name: rstudio ec2 vm check
  hosts: rstudio
  gather_facts: false
  tasks:
    - name: rstudio vm dns record
      delegate_to: localhost
      route53:
        state: present
        overwrite: true
        zone: uws.talkingpts.org
        ttl: 600
        type: A
        record: "{{ ansible_host }}"
        value: "{{ vm_public_ip_address}}"
      when: vm_public_ip_address
