---
- name: rstudio ec2 vm teardown
  hosts: rstudio_teardown
  gather_facts: true
  tasks:

    - name: teardown rstudio vm
      delegate_to: localhost
      ec2_instance_info:
        filters:
          "tag:Name": "{{ inventory_hostname }}"
      register: teardown_vm

    - name: teardown rstudio vm dns record
      delegate_to: localhost
      route53:
        state: absent
        zone: uws.talkingpts.org
        record: "{{ ansible_host }}"
        value: "{{ teardown_vm.instances.0.public_dns_name }}."
        type: CNAME

    - name: teardown rstudio vm stop
      delegate_to: localhost
      ec2:
        state: stopped
        wait: yes
        wait_timeout: 600
        instance_id: "{{ teardown_vm.instances.0.instance_id }}"
        termination_protection: false
