---
- name: rstudio ec2 vm
  hosts: rstudio
  gather_facts: false
  tasks:

    - name: rstudio vm create
      delegate_to: localhost
      ec2:
        monitoring: false
        termination_protection: true
        key_name: asbhost-rstudio
        group: rstudio-sg
        ebs_optimized: false
        volumes:
          - device_name: /dev/xvda
            volume_type: gp3
            volume_size: 10
            delete_on_termination: true
            encrypted: true
        image: "{{ debian_ami }}"
        vpc_subnet_id: "{{ vm_subnet }}"
        instance_type: "{{ vm_type }}"
        instance_tags:
          Name: "{{ inventory_hostname }}"
        exact_count: 1
        count_tag:
          Name: "{{ inventory_hostname }}"

    - name: rstudio vm running
      delegate_to: localhost
      ec2:
        state: running
        wait: true
        wait_timeout: 600
        instance_tags:
          Name: "{{ inventory_hostname }}"
