---
- name: teardown rstudio ec2
  hosts: ec2vpc
  gather_facts: false
  tasks:

    - name: rstudio net info
      delegate_to: localhost
      ec2_vpc_net_info:
        filters:
          "tag:Name": rstudio-vpc
      register: rstudio_net

    - name: rstudio route table info
      delegate_to: localhost
      ec2_vpc_route_table_info:
        filters:
          "tag:Name": rstudio-subnet
      register: rstudio_rtb

    - name: rstudio subnet info
      delegate_to: localhost
      ec2_vpc_subnet_info:
        filters:
          "tag:Name": rstudio-subnet
      register: rstudio_subnet

    - name: rstudio group info
      delegate_to: localhost
      ec2_group_info:
        filters:
          group-name:
            - rstudio-sg
      register: rstudio_sg

    - name: teardown ec2 group
      delegate_to: localhost
      ec2_group:
        state: absent
        group_id: "{{ item.group_id }}"
      loop: "{{ rstudio_sg.security_groups }}"
      when: rstudio_sg.security_groups

    - name: teardown subnet route table
      delegate_to: localhost
      ec2_vpc_route_table:
        state: absent
        route_table_id: "{{ item.id }}"
        vpc_id: "{{ item.vpc_id }}"
      loop: "{{ rstudio_rtb.route_tables }}"
      when: rstudio_rtb.route_tables

    - name: teardown subnet
      delegate_to: localhost
      ec2_vpc_subnet:
        state: absent
        vpc_id: "{{ item.vpc_id }}"
        cidr: "{{ ec2vpc_rstudio }}"
      loop: "{{ rstudio_net.vpcs }}"
      when: rstudio_net.vpcs

    - name: teardown internet gateway
      delegate_to: localhost
      ec2_vpc_igw:
        state: absent
        vpc_id: "{{ item.vpc_id }}"
      loop: "{{ rstudio_net.vpcs }}"
      when: rstudio_net.vpcs

    - name: teardown net
      delegate_to: localhost
      ec2_vpc_net:
        state: absent
        name: rstudio-vpc
        cidr_block: "{{ ec2vpc_block }}"
