---
- name: RStudio ec2 vm check
  hosts: rstudio
  gather_facts: false
  tasks:

    - name: RStudio vm running
      delegate_to: localhost
      amazon.aws.ec2_instance_info:
        filters:
          availability-zone: "{{ aws_zone }}"
          "tag:Name": "{{ inventory_hostname }}"
          instance-state-name: running
      register: rstudio_vm

    - name: RStudio vm dns record
      delegate_to: localhost
      amazon.aws.route53:
        state: present
        overwrite: true
        zone: "{{ uws_domain }}"
        ttl: 600
        type: CNAME
        record: "{{ ansible_host }}"
        value: "{{ rstudio_vm.instances.0.public_dns_name }}."
      when: rstudio_vm.instances

    - name: RStudio ide dns record
      delegate_to: localhost
      amazon.aws.route53:
        state: present
        overwrite: true
        zone: "{{ uws_domain }}"
        ttl: 600
        type: CNAME
        record: "{{ rstudio_server_name }}"
        value: "{{ rstudio_vm.instances.0.public_dns_name }}."
      when: rstudio_vm.instances

    - name: RStudio jupyter-notebook dns record
      delegate_to: localhost
      amazon.aws.route53:
        state: present
        overwrite: true
        zone: "{{ uws_domain }}"
        ttl: 600
        type: CNAME
        record: "{{ rstudio_jnb_server_name }}"
        value: "{{ rstudio_vm.instances.0.public_dns_name }}."
      when: rstudio_vm.instances
