---
- name: rstudio ec2 vpc
  hosts: localhost
  gather_facts: false
  tasks:
    - ec2_vpc_net:
        name: rstudio-vpc
        state: present
        tags:
          Name: rstudio-vpc
        cidr_block: 172.27.0.0/16
      register: rstudio_vpc
    - name: rstudio subnet
      ec2_vpc_subnet:
        state: present
        assign_instances_ipv6: false
        map_public: true
        cidr: 172.27.1.0/24
        vpc_id: "{{ rstudio_vpc.vpc.id }}"
        tags:
          Name: rstudio-subnet
