---
- name: rstudio ec2 vpc
  hosts: localhost
  gather_facts: false
  tasks:

    - name: rstudio net
      delegate_to: localhost
      ec2_vpc_net:
        name: rstudio-vpc
        state: present
        tags:
          Name: rstudio-vpc
        cidr_block: 172.27.0.0/16
      register: rstudio_net

    - name: rstudio subnet
      delegate_to: localhost
      ec2_vpc_subnet:
        state: present
        assign_instances_ipv6: false
        map_public: true
        cidr: 172.27.1.0/24
        vpc_id: "{{ rstudio_net.vpc.id }}"
        tags:
          Name: rstudio-subnet

    - name: rstudio security group
      delegate_to: localhost
      ec2_group:
        name: rstudio-sg
        description: rstudio security group
        state: present
        tags:
          Name: rstudio-sg
        vpc_id: "{{ rstudio_net.vpc.id }}"
        rules:
          - proto: tcp
            ports:
              - 22
              - 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
