---
- name: rstudio ec2 vpc
  hosts: ec2vpc
  gather_facts: false
  tasks:

    #~ - name: rstudio net
      #~ ec2_vpc_net:
        #~ name: rstudio-vpc
        #~ state: present
        #~ tags:
          #~ Name: rstudio-vpc
        #~ cidr_block: "{{ ec2vpc_block }}"
      #~ register: rstudio_net

    #~ - name: rstudio internet gateway
      #~ ec2_vpc_igw:
        #~ state: present
        #~ vpc_id: "{{ rstudio_net.vpc.id }}"
        #~ tags:
          #~ Name: rstudio-igw
      #~ register: rstudio_igw

    #~ - name: rstudio subnet
      #~ ec2_vpc_subnet:
        #~ state: present
        #~ assign_instances_ipv6: false
        #~ map_public: true
        #~ cidr: "{{ ec2vpc_rstudio }}"
        #~ vpc_id: "{{ rstudio_net.vpc.id }}"
        #~ tags:
          #~ Name: rstudio-subnet
      #~ register: rstudio_subnet

    #~ - name: rstudio subnet route table
      #~ ec2_vpc_route_table:
        #~ state: present
        #~ vpc_id: "{{ rstudio_net.vpc.id }}"
        #~ tags:
          #~ Name: rstudio-subnet
        #~ subnets:
          #~ - "{{ rstudio_subnet.subnet.id }}"
        #~ routes:
          #~ - dest: 0.0.0.0/0
            #~ gateway_id: "{{ rstudio_igw.gateway_id }}"

    - name: rstudio security group
      delegate_to: localhost
      ec2_group:
        name: rstudio-sg
        description: rstudio security group
        state: present
        tags:
          Name: rstudio-sg
        #~ vpc_id: "{{ rstudio_net.vpc.id }}"
        vpc_id: "{{ rstudio_vpc }}"
        rules:
          - proto: tcp
            ports:
              - 22
              - 80
              - 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
