---
- name: rstudio upgrade
  hosts: rstudio
  gather_facts: true
  tasks:
    - name: apt update
      become: true
      apt:
        update_cache: true

    - name: apt upgrade
      become: true
      apt:
        name: "*"
        state: latest
        autoclean: true
        autoremove: true

    - name: apt dist-upgrade
      become: true
      apt:
        upgrade: dist
        autoclean: true
        autoremove: true
