---
- name: RStudio upgrade
  hosts: rstudio
  gather_facts: true
  tasks:
    - name: RStudio apt update
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: RStudio apt upgrade
      become: true
      ansible.builtin.apt:
        name: "*"
        state: latest
        autoclean: true
        autoremove: true

    - name: RStudio apt dist-upgrade
      become: true
      ansible.builtin.apt:
        upgrade: dist
        autoclean: true
        autoremove: true
