#~ ---
#~ apiVersion: autoscaling/v2beta2
#~ kind: HorizontalPodAutoscaler
#~ metadata:
  #~ name: web-hpa
  #~ namespace: ${APP_NAMESPACE}
#~ spec:
  #~ scaleTargetRef:
    #~ apiVersion: apps/v1
    #~ kind: Deployment
    #~ name: meteor
  #~ minReplicas: 150
  #~ maxReplicas: 150
  #~ metrics:
  #~ - type: Resource
    #~ resource:
      #~ name: cpu
      #~ target:
        #~ type: Utilization
        #~ averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteor
  namespace: ${APP_NAMESPACE}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: meteor-${APP_NAMESPACE}
  replicas: ${APP_REPLICAS}
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meteor-${APP_NAMESPACE}
    spec:
      terminationGracePeriodSeconds: 150
      containers:
        - image: 789470191893.dkr.ecr.${AWS_REGION}.amazonaws.com/uws:meteor-app-${METEOR_APP}
          imagePullPolicy: IfNotPresent
          name: meteor-web
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 3000
            runAsGroup: 3000
          volumeMounts:
            - name: appenv
              mountPath: "/run/meteor"
              readOnly: true
            - name: app-tmpdir
              mountPath: "/opt/app/bundle/tmp"
            - name: tmpdir
              mountPath: "/tmp"
          env:
            - name: PORT
              value: "3000"
            - name: DISABLE_JOBS
              value: "TRUE"
            - name: NODE_OPTIONS
              value: "--max-old-space-size=${APP_MEMORY}"
          envFrom:
            - secretRef:
                name: meteor-deploy-env
          resources:
            requests:
              cpu: ${APP_CPU}m
              memory: ${APP_MEMORY}Mi
            limits:
              cpu: ${APP_CPU}m
              memory: ${APP_MEMORY}Mi
          readinessProbe:
            exec:
              command:
                - node
                - --version
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 3
      volumes:
        - name: appenv
          secret:
            secretName: meteor-app-env
        - name: app-tmpdir
          emptyDir: {}
        - name: tmpdir
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: meteor
  namespace: ${APP_NAMESPACE}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor-${APP_NAMESPACE}
