---
apiVersion: v1
kind: Service
metadata:
  name: meteor-web-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteor-web-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: meteor-web
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meteor-web
    spec:
      containers:
        - image: 789470191893.dkr.ecr.us-west-2.amazonaws.com/uws:meteor-app-2.1.3-2579-g1e4d18e50
          imagePullPolicy: IfNotPresent
          name: meteor-web
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 3000
            runAsGroup: 3000
          envFrom:
            - secretRef:
                name: meteor-web-env
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: meteor-web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meteor-web-deployment
  minReplicas: 5
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
