---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
  namespace: web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meteor
  minReplicas: 50
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteor
  namespace: web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: meteor-web
  replicas: 50
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meteor-web
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - image: 789470191893.dkr.ecr.us-east-2.amazonaws.com/uws:meteor-app-2.44.1-d948c909
          imagePullPolicy: IfNotPresent
          name: meteor-web
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 3000
            runAsGroup: 3000
          volumeMounts:
            - name: appenv
              mountPath: "/run/meteor"
              readOnly: true
            - name: app-tmpdir
              mountPath: "/opt/app/bundle/tmp"
            - name: tmpdir
              mountPath: "/tmp"
          env:
            - name: PORT
              value: "3000"
            - name: DISABLE_JOBS
              value: "TRUE"
          resources:
            requests:
              cpu: 900m
            limits:
              cpu: 1000m
          readinessProbe:
            exec:
              command:
                - node
                - --version
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 15
      volumes:
        - name: appenv
          secret:
            secretName: meteor-app-env
        - name: app-tmpdir
          emptyDir: {}
        - name: tmpdir
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: meteor
  namespace: web
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor-web
