---
apiVersion: v1
kind: Service
metadata:
  name: meteor-web-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteor-web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: meteor-web
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meteor-web
    spec:
      containers:
        - image: 789470191893.dkr.ecr.us-west-2.amazonaws.com/uws:meteor-app-2.1.3-2468-g7b122646f
          imagePullPolicy: IfNotPresent
          name: meteor-web
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 3000
            runAsGroup: 3000
          volumeMounts:
            - name: appenv
              mountPath: "/run/meteor"
              readOnly: true
          env:
            - name: PORT
              value: "3000"
            - name: DISABLE_JOBS
              value: "TRUE"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              httpHeaders:
                - name: User-Agent
                  value: k8s-check-ready
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              httpHeaders:
                - name: User-Agent
                  value: k8s-check-live
            initialDelaySeconds: 15
            periodSeconds: 15
      volumes:
        - name: appenv
          secret:
            secretName: meteor-web-env
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: meteor-web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meteor-web
  minReplicas: 5
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
