FROM uws/base-2305

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="230818"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh munin-node psmisc procps munin-plugins-core munin-plugins-extra \
	&& rm -vf /etc/munin/plugins/*

ENV MN munin-contrib
ENV MR uruws/${MN}
ENV MV 1f08cd1d8b8f09f9f4e7a2045dd1e1888c48072a
RUN wget -q -O munin-contrib.tgz \
	https://github.com/${MR}/archive/${MV}.tar.gz \
	&& tar -xzf munin-contrib.tgz \
	&& rm -vf munin-contrib.tgz \
	&& mkdir -vp /uws/munin \
	&& mv -vf ${MN}-${MV} /uws/munin/contrib

# mongodb plugins deps
RUN /root/bin/apt-install.sh python3-pymongo

COPY ./utils /root/bin
RUN chmod -v 0750 /root/bin /root/bin/*.sh

COPY --chown=root:uws ./build/uwsbot-stats.bin /uws/bin/uwsbot-stats
RUN chmod -v 0750 /uws/bin/uwsbot-stats

COPY --chown=root:uws ./build/uwsbot-stats.env /uws/etc/env/bot/stats
RUN chmod -v 0640 /uws/etc/env/bot/stats

COPY --chown=root:uws ./build/uwsbot-plugin.conf /etc/munin/plugin-conf.d/uwsbot
RUN chmod -v 0640 /etc/munin/plugin-conf.d/uwsbot

COPY --chown=root:uws ./build/api-job-stats.bin /uws/bin/api-job-stats
RUN chmod -v 0750 /uws/bin/api-job-stats

RUN install -v -d -o root -g uws -m 0750 /uws/etc/ca /uws/lib

COPY --chown=root:uws ./plugins/bin/offlinepage.sh /uws/bin/offlinepage.sh
COPY --chown=root:uws ./plugins/bin/mnpl.sh /uws/bin/mnpl.sh
COPY --chown=root:uws ./plugins/lib /uws/lib/plugins

RUN chmod -v 0750 /uws/bin/mnpl.sh \
	/uws/bin/offlinepage.sh

COPY --chown=root:uws ./plugin-conf.d/uws /etc/munin/plugin-conf.d/uws
RUN chmod -v 0640 /etc/munin/plugin-conf.d/uws

USER root:uws
WORKDIR /root

RUN python3 -m compileall -q /uws/lib/plugins

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

ENTRYPOINT exec /root/bin/mn-start.sh
