FROM uws/base-2211

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="221116"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh ssl-cert msmtp-mta bsd-mailx rsyslog

RUN adduser uws ssl-cert \
	&& adduser uws msmtp

RUN install -v -d -o root -g msmtp -m 0750 /srv/etc \
	&& install -v -d -o root -g msmtp -m 0750 /srv/etc/ca

RUN echo 'mailx.uws.talkingpts.org' >/etc/mailname

COPY ./files/etc/aliases /etc/
RUN chmod -v 0644 /etc/aliases

COPY ./files/etc/msmtprc /etc/
RUN chmod -v 0644 /etc/msmtprc

RUN echo 'set mta=/usr/bin/msmtp' >>/etc/mail.rc

COPY ./files/etc/rsyslog.conf /etc/
COPY ./files/etc/rsyslog.d/ /etc/rsyslog.d/
