FROM uws/base-2305

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="230522"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh ssl-cert msmtp-mta bsd-mailx rsyslog

RUN install -v -m 0444 -o root -g root /etc/ssl/private/ssl-cert-snakeoil.key /etc/opt/ssl-cert-snakeoil.key

RUN echo 'uws.talkingpts.org' >/etc/mailname

RUN echo 'set mta=/usr/bin/msmtp' >>/etc/mail.rc

COPY ./files/etc/rsyslog.conf /etc/
COPY ./files/etc/rsyslog.d/ /etc/rsyslog.d/

RUN install -v -d -m 0750 -o root -g root /etc/opt/root \
	&& ln -vsf /etc/opt/root/msmtprc /root/.msmtprc

RUN install -v -d -m 0750 -o uws -g uws /etc/opt/uws \
	&& ln -vsf /etc/opt/uws/msmtprc /home/uws/.msmtprc

RUN install -v -d -m 0750 -o uwsops -g uwsops /etc/opt/uwsops \
	&& ln -vsf /etc/opt/uwsops/msmtprc /home/uwsops/.msmtprc

RUN install -v -d -m 0750 -o nobody -g nogroup /etc/opt/nobody \
	&& ln -vsf /etc/opt/nobody/msmtprc /etc/msmtprc
