FROM uws/base-2305

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="230522"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh ssl-cert msmtp-mta bsd-mailx rsyslog

RUN adduser uws ssl-cert \
	&& adduser uws msmtp \
	&& adduser uwsops msmtp

RUN install -v -d -o root -g msmtp -m 0750 /srv/etc \
	&& install -v -d -o root -g msmtp -m 0750 /srv/etc/ca

RUN install -v -m 0444 -o root -g root /etc/ssl/private/ssl-cert-snakeoil.key /etc/opt/ssl-cert-snakeoil.key

RUN echo 'uws.talkingpts.org' >/etc/mailname

COPY ./files/etc/aliases /etc/
RUN chmod -v 0644 /etc/aliases

# internal postfix
##COPY ./files/etc/msmtprc /etc/
##RUN chmod -v 0644 /etc/msmtprc

# custom config
RUN ln -vsf /etc/opt/uws/msmtprc /home/uws/.msmtprc

RUN echo 'set mta=/usr/bin/msmtp' >>/etc/mail.rc

COPY ./files/etc/rsyslog.conf /etc/
COPY ./files/etc/rsyslog.d/ /etc/rsyslog.d/
