FROM uws/base-2305

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="230704"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh ssl-cert msmtp-mta bsd-mailx rsyslog

RUN echo 'uws.talkingpts.org' >/etc/mailname
RUN echo 'set mta=/usr/bin/msmtp' >>/etc/mail.rc

COPY --chown=root:root ./files/etc/aliases /etc/
RUN chmod -v 0444 /etc/aliases

COPY --chown=root:root ./files/etc/msmtprc /etc/
RUN chmod -v 0444 /etc/msmtprc

COPY ./files/etc/rsyslog.conf /etc/
COPY ./files/etc/rsyslog.d/ /etc/rsyslog.d/

RUN install -v -d -m 0755 -o root -g root /etc/opt/mailx \
	&& install -v -d -m 0750 -o root -g root /srv/mailx

RUN install -v -m 0444 -o root -g root \
	/etc/ssl/private/ssl-cert-snakeoil.key \
	/etc/opt/mailx/ssl-cert-snakeoil.key

COPY ./files/bin/msmtprc-install.sh /root/bin/
RUN chmod -v 0750 /root/bin/msmtprc-install.sh

RUN ln -svf    /etc/opt/mailx/uws/msmtprc    /home/uws/.msmtprc \
	&& ln -svf /etc/opt/mailx/uwsops/msmtprc /home/uwsops/.msmtprc \
	&& ln -svf /etc/opt/mailx/root/msmtprc   /root/.msmtprc \
	&& ln -svf /etc/opt/mailx/nobody/msmtprc /etc/msmtprc
