FROM uws/python-2211

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="221222"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

COPY --chown=root:uws ./utils /usr/local/bin
RUN chmod -v 0750 /usr/local/bin/*.sh

USER uws:uws
WORKDIR /home/uws

ENV USER uws
ENV HOME /home/uws

ENTRYPOINT exec /usr/local/bin/entrypoint.sh
