---
- name: Fail2ban install
  become: true
  ansible.builtin.apt:
    pkg:
      - fail2ban
  tags:
    - apt

- name: Fail2ban config
  become: true
  ansible.builtin.template:
    src: fail2ban.conf
    dest: /etc/fail2ban/jail.d/zzzuws.conf
    owner: root
    group: uws
    mode: '0640'
  notify:
    - Fail2ban restart
  tags:
    - fail2ban
