#!/bin/sh
set -eu

appver=${1:?'app version?'}

set -x

export TAPO_ENV="${SRMNT_ENV}"
export TAPO_NAMESPACE="${SRMNT_NAMESPACE}"

export TAPO_REPLICAS="${SRMNT_WEB_REPLICAS}"
export TAPO_REPLICAS_MAX="${SRMNT_WEB_REPLICAS_MAX}"
export TAPO_MEMORY="${SRMNT_WEB_MEMORY}"
export TAPO_CPU_REQ="${SRMNT_WEB_CPU_REQ}"
export TAPO_CPU_MAX="${SRMNT_WEB_CPU_MAX}"
export TAPO_HPA_ENABLE="${SRMNT_WEB_HPA_ENABLE}"
export TAPO_HPA_CPU="${SRMNT_WEB_HPA_CPU}"

export TAPO_CDN_NAMESPACE="${SRMNT_NAMESPACE}"
export TAPO_CDN_REPLICAS="${SRMNT_CDN_REPLICAS}"
export TAPO_CDN_REPLICAS_MAX="${SRMNT_CDN_REPLICAS_MAX}"
export TAPO_CDN_MEMORY="${SRMNT_CDN_MEMORY}"
export TAPO_CDN_CPU_REQ="${SRMNT_CDN_CPU_REQ}"
export TAPO_CDN_CPU_MAX="${SRMNT_CDN_CPU_MAX}"
export TAPO_CDN_HPA_ENABLE="${SRMNT_CDN_HPA_ENABLE}"
export TAPO_CDN_HPA_CPU="${SRMNT_CDN_HPA_CPU}"

export TAPO_API_NAMESPACE="${SRMNT_NAMESPACE}"
export TAPO_API_REPLICAS="${SRMNT_API_REPLICAS}"
export TAPO_API_REPLICAS_MAX="${SRMNT_API_REPLICAS_MAX}"
export TAPO_API_MEMORY="${SRMNT_API_MEMORY}"
export TAPO_API_CPU_REQ="${SRMNT_API_CPU_REQ}"
export TAPO_API_CPU_MAX="${SRMNT_API_CPU_MAX}"
export TAPO_API_HPA_ENABLE="${SRMNT_API_HPA_ENABLE}"
export TAPO_API_HPA_CPU="${SRMNT_API_HPA_CPU}"

export TAPO_WORKER_NAMESPACE="${SRMNT_WORKER_NAMESPACE}"
export TAPO_WORKER_REPLICAS="${SRMNT_WORKER_REPLICAS}"
export TAPO_WORKER_REPLICAS_MAX="${SRMNT_WORKER_REPLICAS_MAX}"
export TAPO_WORKER_MEMORY="${SRMNT_WORKER_MEMORY}"
export TAPO_WORKER_CPU_REQ="${SRMNT_WORKER_CPU_REQ}"
export TAPO_WORKER_CPU_MAX="${SRMNT_WORKER_CPU_MAX}"
export TAPO_WORKER_HPA_ENABLE="${SRMNT_WORKER_HPA_ENABLE}"
export TAPO_WORKER_HPA_CPU="${SRMNT_WORKER_HPA_CPU}"

exec ~/pod/tapo/all/deploy.sh "${appver}"
