#!/bin/sh
set -eu

appver=${1:?'app version?'}

set -x

export TAPO_ENV="${SRMNT_ENV}"
export TAPO_NAMESPACE="${SRMNT_NAMESPACE}"

export TAPO_REPLICAS="${SRMNT_WEB_REPLICAS}"
export TAPO_CPU_REQ="${SRMNT_WEB_CPU_REQ}"
export TAPO_CPU_MAX="${SRMNT_WEB_CPU_MAX}"

export TAPO_CDN_REPLICAS="${SRMNT_CDN_REPLICAS}"
export TAPO_CDN_REPLICAS_MAX="${SRMNT_CDN_REPLICAS_MAX}"
export TAPO_CDN_CPU_REQ="${SRMNT_CDN_CPU_REQ}"
export TAPO_CDN_CPU_MAX="${SRMNT_CDN_CPU_MAX}"
export TAPO_CDN_HPA_ENABLE="${SRMNT_CDN_HPA_ENABLE}"
export TAPO_CDN_HPA_CPU="${SRMNT_CDN_HPA_CPU}"

export TAPO_API_REPLICAS="${SRMNT_API_REPLICAS}"
export TAPO_API_CPU_REQ="${SRMNT_API_CPU_REQ}"
export TAPO_API_CPU_MAX="${SRMNT_API_CPU_MAX}"

export TAPO_WORKER_NAMESPACE="${SRMNT_WORKER_NAMESPACE}"
export TAPO_WORKER_REPLICAS="${SRMNT_WORKER_REPLICAS}"
export TAPO_WORKER_CPU_REQ="${SRMNT_WORKER_CPU_REQ}"
export TAPO_WORKER_CPU_MAX="${SRMNT_WORKER_CPU_MAX}"

exec ~/pod/tapo/all/deploy.sh "${appver}"
