---
- name: apt install
  become: yes
  apt:
    pkg:
      - awscli
      - cloud-init

- name: cloud-init setup
  become: yes
  template:
    src: cloud-init/00_setup.cfg
    dest: /etc/cloud/cloud.cfg.d/99zzzuws_00_setup.cfg
    owner: root
    group: root
    mode: '0640'

- name: admin home dir
  become: yes
  file:
    state: directory
    path: /home/admin
    owner: admin
    group: admin
    mode: '0750'
