#!/bin/sh
set -eu

mkdir -vp /srv/run
chown -v root:root /srv/run
chmod -v 0755 /srv/run

mkdir -vp /srv/uws
chown -v uws:uws /srv/uws
chmod -v 0750 /srv/uws

chmod -v 0750 ~admin
chmod -v 0750 ~uws

chown -v uws:uws /uws
chown -R uws:uws /srv/uws

systemctl daemon-reload

exit 0
