#!/bin/sh
set -eu

if ! test -d ~admin/uws.git; then
	sudo -u admin git init --bare ~admin/uws.git
fi

chown -v root:admin /uws/git-uws*.sh
chmod -v 0750 /uws/git-uws*.sh

install -o root -g admin -m 0750 /uws/git-uws-update.sh ~admin/uws.git/hooks/update

if ! test -d ~admin/deploy; then
	sudo -u admin git clone ~admin/uws.git ~admin/deploy
fi

exit 0
