#!/bin/sh
set -eu

DIRS='/srv/acme/challenge /srv/acme/cert /srv/acme/key /srv/acme/req /srv/acme/tmp'
WWW_DIRS='/srv/acme/challenge'

mkdir -vp ${DIRS}
chown -v uws:uws ${DIRS}
chmod -v 0750 ${DIRS}
chown -v uws:www-data ${WWW_DIRS}
chmod -v 0770 ${WWW_DIRS}

export ACME_HOME=/srv/acme
ACME=/srv/uws/deploy/srv/acme/cmd.sh

if ! test -s ${ACME_HOME}/key/account.key; then
	${ACME} keygen.sh account
fi

exit 0
