#!/bin/sh
set -eu

DIRS='/uws/munin /srv/munin /srv/etc/munin'
chown -v root:uws ${DIRS}
chmod -v 0750 ${DIRS}

chmod -v 0755 /uws/munin/service-start.sh

if ! systemctl is-enabled uws-munin.service; then
	systemctl enable uws-munin.service
	systemctl start uws-munin
fi

/uws/bin/service-restart.sh uws-munin /uws/munin/service-start.sh /srv/etc/munin

exit 0
