#!/bin/sh
set -eu

if ! systemctl is-enabled uws-munin-backend.service; then
	systemctl enable uws-munin-backend.service
	service uws-munin-backend start
fi

/uws/bin/service-restart.sh uws-munin-backend

exit 0
