---
uws_domain: uws.talkingpts.org

ansible_user: admin
ansible_host: "{{ inventory_hostname }}.{{ uws_domain }}"

# debian-11-amd64-20211011-792
debian_ami: ami-0a04b49ce7d910659

vm_type: t3a.small

debian_release: bullseye

uws_authorized_key:
  - jrmsgit

postconf_mailname: ""
postconf_smtps: no

uwsca_smtps: smtps/211006
uws_smtps: "ops.{{ uws_domain }}"
uws_smtps_port: 465
