---
- name: restart rstudio-server
  become: true
  service:
    name: rstudio-server
    state: restarted
  tags:
    - rstudio

- name: reload systemd
  become: true
  systemd:
    daemon_reload: true
  tags:
    - rstudio
