---
- name: restart rstudio-server
  become: yes
  service:
    name: rstudio-server
    state: restarted
  tags:
    - rstudio

- name: reload systemd
  become: yes
  systemd:
    daemon_reload: yes
  tags:
    - rstudio
