---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
  labels:
    k8s-app: node-exporter
  name: node-exporter
  namespace: mon
spec:
  selector:
    matchLabels:
      k8s-app: node-exporter
  template:
    metadata:
      labels:
        k8s-app: node-exporter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values:
                - fargate
      containers:
        - image: quay.io/prometheus/node-exporter:v1.1.2
          imagePullPolicy: IfNotPresent
          name: node-exporter
          args:
            - "--path.rootfs=/host"
          resources:
            requests:
              cpu: 1m
              memory: 2Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
          ports:
            - containerPort: 9100
          volumeMounts:
            - mountPath: "/host"
              name: host-rootfs
              mountPropagation: HostToContainer
              readOnly: true
      volumes:
        - name: host-rootfs
          hostPath:
            type: Directory
            path: "/"
