---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: mon
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
    spec:
      containers:
        - image: prom/prometheus:v2.27.1
          imagePullPolicy: IfNotPresent
          name: prometheus
          ports:
            - containerPort: 9090
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
          resources:
            requests:
              cpu: 1m
              memory: 20Mi
          volumeMounts:
            - name: promcfg
              mountPath: "/etc/prometheus"
              readOnly: true
      volumes:
        - name: promcfg
          configMap:
            name: promcfg
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: mon
spec:
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus
