---
apiVersion: v1
kind: Service
metadata:
  name: munin-web
spec:
  type: ExternalName
  externalName: munin-web.mon.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: k8smon
spec:
  type: ExternalName
  externalName: k8s.mon.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: podtest
spec:
  ports:
    - port: 2800
      targetPort: 2800
      protocol: TCP
  selector:
    app.kubernetes.io/name: podtest
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  annotations:
    # https://haproxy-ingress.github.io/docs/configuration/keys/#auth-tls
    haproxy-ingress.github.io/auth-tls-secret: "uwsca-ops"
    haproxy-ingress.github.io/auth-tls-strict: "true"
    haproxy-ingress.github.io/auth-tls-verify-client: "on"
  labels:
    uws.t.o/ingress-class: ${HPX_NAMESPACE}hpx
spec:
  ingressClassName: ${HPX_NAMESPACE}hpx
  tls:
    - hosts:
        - ${HPX_HOSTNAME}.talkingpts.org
      secretName: ${HPX_TLS}
  rules:
    - host: ${HPX_HOSTNAME}.talkingpts.org
      http:
        paths:
          # podtest
          - path: /podtest/
            pathType: Prefix
            backend:
              service:
                name: podtest
                port:
                  number: 2800
          # munin
          - path: /munin/
            pathType: Prefix
            backend:
              service:
                name: munin-web
                port:
                  number: 80
          - path: /munin-cgi/
            pathType: Prefix
            backend:
              service:
                name: munin-web
                port:
                  number: 80
          # k8smon
          - path: /k8smon/
            pathType: Prefix
            backend:
              service:
                name: k8smon
                port:
                  number: 2800
