---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: meteor-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meteor-worker
  minReplicas: 200
  maxReplicas: 200
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteor-worker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: meteor-worker
  replicas: 200
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meteor-worker
    spec:
      containers:
        - image: 789470191893.dkr.ecr.us-east-2.amazonaws.com/uws:meteor-app-2.44.0-cae33029
          imagePullPolicy: IfNotPresent
          name: meteor-worker
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 3000
            runAsGroup: 3000
          volumeMounts:
            - name: appenv
              mountPath: "/run/meteor"
              readOnly: true
            - name: app-tmpdir
              mountPath: "/opt/app/bundle/tmp"
            - name: tmpdir
              mountPath: "/tmp"
          env:
            - name: PORT
              value: "3000"
          resources:
            requests:
              cpu: 900m
            limits:
              cpu: 1000m
      volumes:
        - name: appenv
          secret:
            secretName: meteor-worker-env
        - name: app-tmpdir
          emptyDir: {}
        - name: tmpdir
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: meteor-worker-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor-worker
