---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteor
  namespace: worker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: meteor-worker
  replicas: ${APP_REPLICAS}
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meteor-worker
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - image: 789470191893.dkr.ecr.${AWS_REGION}.amazonaws.com/uws:meteor-app-${METEOR_APP}
          imagePullPolicy: IfNotPresent
          name: meteor-worker
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 3000
            runAsGroup: 3000
          volumeMounts:
            - name: appenv
              mountPath: "/run/meteor"
              readOnly: true
            - name: app-tmpdir
              mountPath: "/opt/app/bundle/tmp"
            - name: tmpdir
              mountPath: "/tmp"
          env:
            - name: PORT
              value: "3000"
            - name: METEOR_POLLING_INTERVAL_MS
              value: "300"
            - name: METEOR_POLLING_THROTTLE_MS
              value: "50"
            - name: UWSAPP_MEMORY
              value: "${METEOR_WORKER_MEMORY}"
            - name: UWSAPP_CLUSTER
              value: "${APP_CLUSTER}"
            - name: UWSAPP_DEPLOY
              value: "${APP_DEPLOY}"
            - name: UWSAPP_ENV
              value: "${APP_ENV}"
            - name: UWSAPP_NAMESPACE
              value: "${APP_NAMESPACE}"
            - name: UWSAPP_VERSION
              value: "${APP_VERSION}"
          resources:
            requests:
              cpu: ${METEOR_WORKER_CPU}m
            limits:
              cpu: ${METEOR_WORKER_CPU}m
          readinessProbe:
            exec:
              command:
                - node
                - --version
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: appenv
          secret:
            secretName: meteor-app-env
        - name: app-tmpdir
          emptyDir: {}
        - name: tmpdir
          emptyDir: {}
