#~ ---
#~ apiVersion: autoscaling/v2beta2
#~ kind: HorizontalPodAutoscaler
#~ metadata:
  #~ name: worker-hpa
  #~ namespace: worker
#~ spec:
  #~ scaleTargetRef:
    #~ apiVersion: apps/v1
    #~ kind: Deployment
    #~ name: meteor
  #~ minReplicas: 50
  #~ maxReplicas: 50
  #~ metrics:
  #~ - type: Resource
    #~ resource:
      #~ name: cpu
      #~ target:
        #~ type: Utilization
        #~ averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteor
  namespace: worker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: meteor-worker
  replicas: 50
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meteor-worker
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - image: 789470191893.dkr.ecr.us-east-2.amazonaws.com/uws:meteor-app-2.45.1-3bdc5874
          imagePullPolicy: IfNotPresent
          name: meteor-worker
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 3000
            runAsGroup: 3000
          volumeMounts:
            - name: appenv
              mountPath: "/run/meteor"
              readOnly: true
            - name: app-tmpdir
              mountPath: "/opt/app/bundle/tmp"
            - name: tmpdir
              mountPath: "/tmp"
          env:
            - name: PORT
              value: "3000"
            - name: METEOR_POLLING_INTERVAL_MS
              value: "300"
            - name: METEOR_POLLING_THROTTLE_MS
              value: "50"
            - name: SNOWFLAKE_SYNC_ENABLED
              value: "TRUE"
          resources:
            requests:
              cpu: 400m
              memory: 900Mi
          readinessProbe:
            exec:
              command:
                - node
                - --version
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 3
      volumes:
        - name: appenv
          secret:
            secretName: meteor-app-env
        - name: app-tmpdir
          emptyDir: {}
        - name: tmpdir
          emptyDir: {}
