---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteor-worker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: meteor-worker
  replicas: 40
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meteor-worker
    spec:
      containers:
        - image: 789470191893.dkr.ecr.us-west-2.amazonaws.com/uws:meteor-app-2.1.3-2468-g7b122646f-2
          imagePullPolicy: IfNotPresent
          name: meteor-worker
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 3000
            runAsGroup: 3000
          volumeMounts:
            - name: appenv
              mountPath: "/run/meteor"
              readOnly: true
          env:
            - name: PORT
              value: "3000"
      volumes:
        - name: appenv
          secret:
            secretName: meteor-worker-env
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: meteor-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meteor-worker
  minReplicas: 40
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
