---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteor
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: meteor
  replicas: ${INFRA_UI_REPLICAS}
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meteor
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: 789470191893.dkr.ecr.${AWS_REGION}.amazonaws.com/uws:meteor-infra-ui-${METEOR_APP}
          imagePullPolicy: IfNotPresent
          name: meteor
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 3000
            runAsGroup: 3000
          volumeMounts:
            - name: appenv
              mountPath: "/run/meteor"
              readOnly: true
          env:
            - name: PORT
              value: "3000"
            - name: UWSAPP_MEMORY
              value: "3200"
            - name: UWSAPP_CLUSTER
              value: "${APP_CLUSTER}"
            - name: UWSAPP_DEPLOY
              value: "${APP_DEPLOY}"
            - name: UWSAPP_ENV
              value: "${APP_ENV}"
            - name: UWSAPP_NAMESPACE
              value: "${APP_NAMESPACE}"
            - name: UWSAPP_VERSION
              value: "${APP_VERSION}"
          resources:
            requests:
              cpu: 800m
              memory: 3200Mi
            limits:
              cpu: 800m
              memory: 3200Mi
          readinessProbe:
            exec:
              command:
                - node
                - --version
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: appenv
          secret:
            secretName: appenv
---
apiVersion: v1
kind: Service
metadata:
  name: meteor
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteor1
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteor2
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteor3
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteor4
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteor5
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteor6
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteor7
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteor8
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteor9
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteora
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteorb
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteorc
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteord
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteore
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteorf
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteorg
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteorh
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteori
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteorj
  namespace: infra-ui-${INFRA_UI_ENV}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
