version: '3.6'

networks:
  default:
    driver: bridge

services:
  app:
    image: 789470191893.dkr.ecr.us-east-1.amazonaws.com/uws:munin-node
    container_name: uws-munin-node-app-service
    volumes:
      - ./app:/srv/etc/munin-node:ro
    restart: on-failure
    ports:
      - 4950:4949
    networks:
      - default

  www:
    image: 789470191893.dkr.ecr.us-east-1.amazonaws.com/uws:munin-node
    container_name: uws-munin-node-www-service
    volumes:
      - ./www:/srv/etc/munin-node:ro
    restart: on-failure
    ports:
      - 4951:4949
    networks:
      - default
