---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment
  namespace: nlp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nlp-sentiment
  replicas: 20
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nlp-sentiment
    spec:
      containers:
        - image: 789470191893.dkr.ecr.${AWS_REGION}.amazonaws.com/uws:nlp-sentiment-${APP_VERSION}
          imagePullPolicy: IfNotPresent
          name: nlp-sentiment
          ports:
            - containerPort: 5200
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 3000
            runAsGroup: 1001
          resources:
            requests:
              cpu: 800m
              memory: 3000Mi
            limits:
              cpu: 800m
              memory: 3000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment
  namespace: nlp
spec:
  ports:
    - port: 5200
      targetPort: 5200
      protocol: TCP
  selector:
    app.kubernetes.io/name: nlp-sentiment
