---
apiVersion: v1
kind: Service
metadata:
  name: munin-web
  namespace: mon
  labels:
    app.kubernetes.io/name: munin-web
spec:
  ports:
  - port: 80
    name: web
  selector:
    app.kubernetes.io/name: munin
---
apiVersion: v1
kind: Service
metadata:
  name: k8s
  namespace: mon
  labels:
    app.kubernetes.io/name: k8s
spec:
  ports:
  - port: 2800
    name: k8smon
  selector:
    app.kubernetes.io/name: k8s
