# from https://cert-manager.io/docs/configuration/acme/
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: acme-staging
spec:
  acme:
    email: jeremias@talkingpts.org
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: acme-staging-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
