FROM uws/python-2211

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="221222"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh python3-venv python3-bottle

RUN install -v -d -m 0750 -o uws -g uwsops /opt/uws

RUN adduser uws uwsops

USER uws:uwsops
WORKDIR /home/uws

ENV USER uws
ENV HOME /home/uws

RUN python3 -m venv --system-site-packages --symlinks /opt/uws/venv

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

COPY --chown=root:uwsops ./utils /usr/local/bin
RUN chmod -v 0750 /usr/local/bin/*.sh

USER uwsops:uwsops
WORKDIR /home/uwsops

ENV USER uwsops
ENV HOME /home/uwsops

ENTRYPOINT exec /usr/local/bin/entrypoint.sh
