FROM uws/base-2305

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="230519"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh proftpd-core proftpd-mod-crypto

COPY ./secret/ssh/ /usr/local/etc/ssh/
RUN chmod -v 0600 /usr/local/etc/ssh/ssh_host_*_key \
	&& chmod -v 0640 /usr/local/etc/ssh/ssh_host_*_key.pub

COPY ./secret/auth/passwd /usr/local/etc/ftp.passwd
RUN chmod -v 0640 /usr/local/etc/ftp.passwd

COPY ./secret/auth/group /usr/local/etc/ftp.group
RUN chmod -v 0640 /usr/local/etc/ftp.group

COPY ./config/ /usr/local/etc/proftpd/
COPY ./entrypoint.sh /usr/local/bin/entrypoint.sh

RUN proftpd -c /usr/local/etc/proftpd/proftpd.conf --configtest

ENTRYPOINT /usr/local/bin/entrypoint.sh
