FROM uws/base-2305

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="230710"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh uuid-runtime

ENV GOPATH /root/go

RUN /root/bin/apt-install.sh golang git \
	&& go install github.com/uruws/mkcert@230710 \
	&& /root/bin/apt-autoremove.sh golang git \
	&& install -v -m 0755 /root/go/bin/mkcert /usr/local/bin/mkcert \
	&& rm -rf /root/go

ENV GOPATH=

RUN chgrp -v uws /usr/local/bin \
	&& chmod -v g+w /usr/local/bin

VOLUME /home/uws/ca

USER uws:uws
WORKDIR /home/uws/ca

ENV USER uws
ENV HOME /home/uws
ENV CAROOT /home/uws/ca
ENV TRUST_STORES system

COPY --chown=uws:uws ./utils /usr/local/bin

CMD exec mkcert
