---
- name: apt install
  become: true
  apt:
    pkg:
      - kali-desktop-xfce
      - bzip2
      - xz-utils
      - net-tools
      - xrdp
      - xorgxrdp
      - xorg
      - xbitmaps
      - dbus-x11
      - bash-completion
  tags:
    - apt
    - kali-apt

- name: xrdp service enable
  become: true
  service:
    name: xrdp
    enabled: true
  notify:
    - restart xrdp
  tags:
    - kali

- name: xrdp options
  become: true
  lineinfile:
    path: /etc/default/xrdp
    regexp: '^XRDP_OPTIONS='
    line: "XRDP_OPTIONS='-p tcp://:3327'"
  notify:
    - restart xrdp
  tags:
    - kali

- name: xrdp users
  become: true
  user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: kali-trusted
    expires: 1666321200
  loop: "{{ kali_xrdp_users }}"
  tags:
    - kali
    - kali-users

- name: vm info
  delegate_to: localhost
  ec2_instance_info:
    filters:
      "tag:Name": "{{ inventory_hostname }}"
  register: kali_vm
  tags:
    - kali
    - kali-vm

- name: debug
  delegate_to: localhost
  debug:
    var: kali_vm.instances.0.instance_id
  tags:
    - kali-vm

- block:
    - name: datafs vol
      delegate_to: localhost
      ec2_vol:
        name: kali-datafs
        instance: "{{ kali_vm.instances.0.instance_id }}"
        encrypted: true
        volume_size: 100
        volume_type: gp2
        device_name: /dev/sdf
        delete_on_termination: false
    - name: make datafs
      become: true
      filesystem:
        dev: /dev/nvme1n1
        fstype: ext4
        opts: -L kali-datafs
    - name: mount datafs
      become: true
      mount:
        path: /data
        src: LABEL=kali-datafs
        fstype: ext4
        state: mounted
    - name: datafs perms
      become: true
      file:
        path: /data
        state: directory
        owner: uws
        group: kali-trusted
        mode: '0770'
    - name: datafs acl
      become: true
      acl:
        path: /data
        entity: www-data
        etype: group
        permissions: r-x
        state: present
  when: kali_public_vm
  tags:
    - kali
    - kali-vm

- name: xrdp service
  become: true
  service:
    name: xrdp
    state: started
  tags:
    - kali

- name: nginx service enable
  become: true
  service:
    name: nginx
    enabled: true
  tags:
    - kali

- name: nginx service
  become: true
  service:
    name: nginx
    state: started
  tags:
    - kali
