---
- name: apt install
  become: yes
  apt:
    pkg:
      - kali-desktop-xfce
      - bzip2
      - xz-utils
      - net-tools
      - xrdp
      - xorgxrdp
      - xorg
      - xbitmaps
      - dbus-x11
  tags:
    - apt
    - kali-apt

- name: xrdp service
  become: yes
  service:
    name: xrdp
    enabled: yes
  notify:
    - restart xrdp
  tags:
    - kali

- name: xrdp options
  become: yes
  lineinfile:
    path: /etc/default/xrdp
    regexp: '^XRDP_OPTIONS='
    line: "XRDP_OPTIONS='-p tcp://:3327'"
  notify:
    - restart xrdp
  tags:
    - kali

- name: xrdp users
  become: yes
  user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: kali-trusted
    expires: 1666321200
  loop: "{{ kali_xrdp_users }}"
  tags:
    - kali
    - kali-users
