---
- name: apt install
  become: yes
  apt:
    pkg:
      - kali-desktop-xfce
      - bzip2
      - xz-utils
      - net-tools
      - xrdp
      - xorgxrdp
      - xorg
      - xbitmaps
      - dbus-x11
  tags:
    - apt
    - kali-apt

- name: xrdp service
  become: yes
  service:
    name: xrdp
    enabled: yes
  notify:
    - restart xrdp
  tags:
    - kali

- name: xrdp options
  become: yes
  lineinfile:
    path: /etc/default/xrdp
    regexp: '^XRDP_OPTIONS='
    line: "XRDP_OPTIONS='-p tcp://:3327'"
  notify:
    - restart xrdp
  tags:
    - kali

- name: xrdp users
  become: yes
  user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: kali-trusted
    expires: 1666321200
  loop: "{{ kali_xrdp_users }}"
  tags:
    - kali
    - kali-users

- name: vm info
  delegate_to: localhost
  ec2_instance_info:
    filters:
      "tag:Name": "{{ inventory_hostname }}"
  register: kali_vm
  tags:
    - kali
    - kali-vm

- name: debug
  delegate_to: localhost
  debug:
    var: kali_vm.instances.0.instance_id
  tags:
    - kali-vm

- block:
    - name: datafs vol
      delegate_to: localhost
      ec2_vol:
        name: kali-datafs
        instance: "{{ kali_vm.instances.0.instance_id }}"
        encrypted: yes
        volume_size: 100
        volume_type: gp2
        device_name: /dev/sdf
        delete_on_termination: no
    - name: make datafs
      become: yes
      filesystem:
        dev: /dev/nvme1n1
        fstype: ext4
        opts: -L kali-datafs
    - name: mount datafs
      become: yes
      mount:
        path: /data
        src: LABEL=kali-datafs
        fstype: ext4
        state: mounted
    - name: datafs perms
      become: yes
      file:
        path: /data
        state: directory
        owner: uws
        group: kali-trusted
        mode: '0771'
  when: vm_public_name == "kando"
  tags:
    - kali
    - kali-vm

#~ - name: tools install
  #~ become: yes
  #~ apt:
    #~ pkg:
      #~ - kali-tools-crypto-stego
      #~ - kali-tools-database
      #~ - kali-tools-exploitation
      #~ - kali-tools-passwords
      #~ - kali-tools-reporting
      #~ - kali-tools-top10
      #~ - kali-tools-vulnerability
      #~ - kali-tools-web
  #~ tags:
    #~ - apt
    #~ - kali-apt
    #~ - kali-tools
