---
- name: Kali apt install
  become: true
  ansible.builtin.apt:
    pkg:
      - kali-desktop-xfce
      - bzip2
      - xz-utils
      - net-tools
      - xrdp
      - xorgxrdp
      - xorg
      - xbitmaps
      - dbus-x11
      - bash-completion
  tags:
    - apt
    - kali-apt

- name: Kali xrdp service enable
  become: true
  ansible.builtin.service:
    name: xrdp
    enabled: true
  notify:
    - restart xrdp
  tags:
    - kali

- name: Kali xrdp options
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/xrdp
    regexp: '^XRDP_OPTIONS='
    line: "XRDP_OPTIONS='-p tcp://:3327'"
  notify:
    - restart xrdp
  tags:
    - kali

- name: Kali xrdp users
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: kali-trusted
    expires: 1666321200
  loop: "{{ kali_xrdp_users }}"
  tags:
    - kali
    - kali-users

- name: Kali vm info
  delegate_to: localhost
  amazon.aws.ec2_instance_info:
    filters:
      "tag:Name": "{{ inventory_hostname }}"
  register: kali_vm
  tags:
    - kali
    - kali-vm

- name: Kali debug
  delegate_to: localhost
  ansible.builtin.debug:
    var: kali_vm.instances.0.instance_id
  tags:
    - kali-vm

- name: Kali datafs
  when: kali_public_vm
  tags:
    - kali
    - kali-vm
  block:
    - name: Kali datafs vol
      delegate_to: localhost
      amazon.aws.ec2_vol:
        name: kali-datafs
        instance: "{{ kali_vm.instances.0.instance_id }}"
        encrypted: true
        volume_size: 100
        volume_type: gp2
        device_name: /dev/sdf
        delete_on_termination: false
    - name: Kali make datafs
      become: true
      community.general.filesystem:
        dev: /dev/nvme1n1
        fstype: ext4
        opts: -L kali-datafs
    - name: Kali mount datafs
      become: true
      ansible.posix.mount:
        path: /data
        src: LABEL=kali-datafs
        fstype: ext4
        state: mounted
    - name: Kali datafs perms
      become: true
      ansible.builtin.file:
        path: /data
        state: directory
        owner: uws
        group: kali-trusted
        mode: '0770'
    - name: Kali datafs acl
      become: true
      ansible.posix.acl:
        path: /data
        entity: www-data
        etype: group
        permissions: r-x
        state: present

- name: Kali xrdp service
  become: true
  ansible.builtin.service:
    name: xrdp
    state: started
  tags:
    - kali

- name: Kali nginx service enable
  become: true
  ansible.builtin.service:
    name: nginx
    enabled: true
  tags:
    - kali

- name: Kali nginx service
  become: true
  ansible.builtin.service:
    name: nginx
    state: started
  tags:
    - kali
