spec:
  ingressClassName: alb
  #~ tls:
    #~ - hosts:
        #~ - ${ALB_HOSTNAME}.talkingpts.org
      #~ secretName: ${HPX_TLS}
  rules:
    - host: ${ALB_HOSTNAME}.talkingpts.org
      http:
        paths:
          # /api/
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: meteor-api
                port:
                  number: 3000
          # /bandwidthCallbackSMS
          - path: /bandwidthCallbackSMS
            pathType: Prefix
            backend:
              service:
                name: meteor-api
                port:
                  number: 3000
          # /coconut_webhook
          - path: /coconut_webhook
            pathType: Prefix
            backend:
              service:
                name: meteor-api
                port:
                  number: 3000
#~ ---
#~ apiVersion: v1
#~ kind: Service
#~ metadata:
  #~ name: meteor-api
#~ spec:
  #~ ports:
    #~ - port: 3000
      #~ targetPort: 3000
      #~ protocol: TCP
  #~ selector:
    #~ app.kubernetes.io/name: meteor-api
