---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ner
  namespace: nlp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nlp-ner
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nlp-ner
    spec:
      containers:
        - image: 789470191893.dkr.ecr.${AWS_REGION}.amazonaws.com/uws:nlp-ner-${APP_VERSION}
          imagePullPolicy: IfNotPresent
          name: nlp-ner
          ports:
            - containerPort: 5100
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 3000
            runAsGroup: 1001
          resources:
            requests:
              cpu: 100m
              memory: 1000Mi
            limits:
              cpu: 100m
              memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ner
  namespace: nlp
spec:
  ports:
    - port: 5100
      targetPort: 5100
      protocol: TCP
  selector:
    app.kubernetes.io/name: nlp-ner
