---
- name: apt install
  become: yes
  apt:
    pkg:
      - iptables
      - iptables-persistent
      - netfilter-persistent
  tags:
    - apt

- name: rules
  become: yes
  template:
    src: iptables/{{ item }}
    dest: /etc/iptables/{{ item }}
    owner: root
    group: root
    mode: '0640'
  loop:
    - rules.v4
    - rules.v6
  notify:
    - reload iptables
  tags:
    - iptables
