---
- name: IPtables install
  become: true
  ansible.builtin.apt:
    pkg:
      - iptables
      - iptables-persistent
      - netfilter-persistent
  tags:
    - apt

- name: IPtables rules
  become: true
  ansible.builtin.template:
    src: iptables/{{ item }}
    dest: /etc/iptables/{{ item }}
    owner: root
    group: root
    mode: '0640'
  loop:
    - rules.v4
    - rules.v6
  register: iptables_rules
  notify:
    - IPtables reload
    - "firewall changed"
  tags:
    - iptables
