---
- name: apt install
  become: yes
  apt:
    pkg:
      - iptables
      - iptables-persistent
      - netfilter-persistent
  tags:
    - apt

- name: rules
  become: yes
  template:
    src: iptables/{{ item }}
    dest: /etc/iptables/{{ item }}
    owner: root
    group: root
    mode: '0640'
  loop:
    - rules.v4
    - rules.v6
  register: iptables_rules
  notify:
    - "firewall changed"
  tags:
    - iptables

- name: reload iptables
  become: yes
  command:
    cmd: service netfilter-persistent reload
    warn: no
  when: iptables_rules is changed
  tags:
    - iptables
