---
apiVersion: v1
kind: Service
metadata:
  name: uwsctl
spec:
  type: ExternalName
  externalName: ctl.uws.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: uwsca
spec:
  type: ExternalName
  externalName: ca.uws.svc.cluster.local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-gateway
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/issuer: acme-prod
    #~ nginx.ingress.kubernetes.io/auth-type: basic
    #~ nginx.ingress.kubernetes.io/auth-secret: basic-auth
    #~ nginx.ingress.kubernetes.io/auth-realm: 'Who are you?'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - devel.uws.talkingpts.org
      secretName: cluster-certificate
  rules:
    - host: devel.uws.talkingpts.org
      http:
        paths:
          - pathType: Prefix
            path: /ca/(.*)
            backend:
              service:
                name: uwsca
                port:
                  number: 2801
          - pathType: Prefix
            path: /(.*)
            backend:
              service:
                name: uwsctl
                port:
                  number: 2800
