---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: ${HPX_NAMESPACE}hpx
spec:
  controller: haproxy-ingress.github.io/controller
  parameters:
    kind: ConfigMap
    name: ${HPX_NAMESPACE}hpx
