#
# https://haproxy-ingress.github.io/docs/configuration/keys/
# https://haproxy-ingress.github.io/docs/configuration/keys/#keys
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "${HPX_NAMESPACE}hpx"
data:
  backend-protocol: "h1"
  # https://haproxy-ingress.github.io/docs/configuration/keys/#auth-tls
  auth-tls-cert-header: "false"
  # https://haproxy-ingress.github.io/docs/configuration/keys/#balance-algorithm
  balance-algorithm: "roundrobin"
  # https://haproxy-ingress.github.io/docs/configuration/keys/#connection
  max-connections: "2000"
  maxconn-server:  "2000"
  maxqueue-server: "10"
  # https://haproxy-ingress.github.io/docs/configuration/keys/#forwardfor
  forwardfor: "add"
  # https://haproxy-ingress.github.io/docs/configuration/keys/#path-type
  path-type: "prefix"
  # https://haproxy-ingress.github.io/docs/configuration/keys/#security
  use-chroot: "true"
  # https://haproxy-ingress.github.io/docs/configuration/keys/#ssl-redirect
  ssl-redirect: "true"
  # https://haproxy-ingress.github.io/docs/configuration/keys/#timeout
  timeout-client:       "50s"
  timeout-client-fin:   "50s"
  timeout-connect:      "5s"
  timeout-http-request: "5s"
  timeout-keep-alive:   "1m"
  timeout-queue:        "5s"
  timeout-server:       "50s"
  timeout-server-fin:   "50s"
  timeout-stop:         "10m"
  timeout-tunnel:       "1h"
