FROM uws/k8s-124-2309

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="231026"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh less shellcheck python3 python3-mypy \
	python3-coverage libjs-jquery libjs-jquery-throttle-debounce \
	libjs-jquery-tablesorter libjs-jquery-isonscreen

RUN install -v -d -m 0750 -o uws -g uws /go /go/src

USER uws:uws
WORKDIR /home/uws

ENV USER uws
ENV HOME /home/uws

ENV GOPATH /go
