FROM uws/base-2211

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="221117"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh less

RUN mkdir -vp /uws/var /uws/etc/env \
	&& chown -vR uws:uws /uws \
	&& chmod -vR 0750 /uws

COPY ./build/uwsbot.bin /usr/local/bin/uwsbot
COPY ./build/uwsbot-stats.bin /usr/local/bin/uwsbot-stats
RUN chmod -v 0755 /usr/local/bin/uwsbot*

COPY --chown=uws:uws ./build/env/bot /uws/etc/env/
RUN chmod -v 0640 /uws/etc/env/bot/*

COPY --chown=uws:uws ./build/uwsbot.docs /uws/share/doc/uwsbot.txt
RUN chmod -v 0640 /uws/share/doc/uwsbot.txt

USER uws:uws
WORKDIR /home/uws

ENV USER uws
ENV HOME /home/uws

ENTRYPOINT ["uwsbot"]
