FROM uws/webapp-2211

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="230203"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh apache2-utils

USER uws:uwsops
WORKDIR /home/uws

ENV USER uws
ENV HOME /home/uws

RUN install -v -d -m 0750 /opt/uws/ab

##COPY --chown=uws:uwsops ./src/requirements.txt /opt/uws/ab/requirements.txt
##RUN /opt/uws/venv/bin/pip install -r /opt/uws/ab/requirements.txt

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

COPY --chown=uws:uwsops ./src /opt/uws/chatbot

USER uws:uwsops
WORKDIR /home/uws

ENV USER uws
ENV HOME /home/uws

RUN /opt/uws/venv/bin/python3 -m compileall /opt/uws/ab

USER uwsops:uwsops
WORKDIR /home/uwsops

ENV USER uwsops
ENV HOME /home/uwsops
ENV UWS_WEBAPP_WORKERS 1
ENV UWS_WEBAPP_PORT 2741

ENTRYPOINT exec /usr/local/bin/entrypoint.sh
