FROM uws/base-testing

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="230201"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh apache2-utils

USER uws:uwsops
WORKDIR /home/uws

ENV USER uws
ENV HOME /home/uws

ENTRYPOINT exec /usr/local/bin/entrypoint.sh
