FROM amazon/aws-cli:2.9.8

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="221221"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

ARG UWS_UID=1000
ARG UWS_GID=1000

RUN echo "uws:x:${UWS_GID}:" >>/etc/group
RUN echo "uws:x:${UWS_UID}:${UWS_GID}:uws:/home/uws:/bin/bash" >>/etc/passwd
RUN echo >>/etc/shadow; echo 'uws:*LOCK*:14600::::::' >>/etc/shadow

RUN mkdir -vp /home/uws \
	&& chown -v uws:uws /aws /home/uws \
	&& chmod -v 0750 /aws /home/uws

RUN install -v -d -m 0750 -o uws -g uws /home/uws/bin

RUN yum install -y --color=never python3

USER uws:uws
WORKDIR /aws

ENV USER uws
ENV HOME /home/uws
ENV PATH /home/uws/.local/bin:${PATH}

ARG UWS_UMASK=0027

RUN printf 'umask %s\n'               ${UWS_UMASK}         >>/home/uws/.profile
RUN printf 'export PATH=%s:${PATH}\n' /home/uws/bin        >>/home/uws/.profile
RUN printf 'source %s\n'              /etc/bashrc          >>/home/uws/.profile
