---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteor
  namespace: meteor-vanilla
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: meteor
  replicas: ${METEOR_VANILLA_REPLICAS}
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meteor
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: 789470191893.dkr.ecr.${AWS_REGION}.amazonaws.com/uws:meteor-vanilla-${METEOR_APP}
          imagePullPolicy: IfNotPresent
          name: meteor
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 3000
            runAsGroup: 3000
          volumeMounts:
            - name: appenv
              mountPath: "/run/meteor"
              readOnly: true
          env:
            - name: PORT
              value: "3000"
            - name: NODE_OPTIONS
              value: "--max-old-space-size=${METEOR_VANILLA_MEMORY}"
            - name: UWSAPP_CLUSTER
              value: "${APP_CLUSTER}"
            - name: UWSAPP_DEPLOY
              value: "${APP_DEPLOY}"
            - name: UWSAPP_ENV
              value: "${APP_ENV}"
            - name: UWSAPP_NAMESPACE
              value: "${APP_NAMESPACE}"
            - name: UWSAPP_VERSION
              value: "${APP_VERSION}"
          resources:
            requests:
              cpu: ${METEOR_VANILLA_CPU}m
              memory: ${METEOR_VANILLA_MEMORY}Mi
            limits:
              cpu: ${METEOR_VANILLA_CPU}m
              memory: ${METEOR_VANILLA_MEMORY}Mi
          readinessProbe:
            exec:
              command:
                - node
                - --version
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: appenv
          secret:
            secretName: appenv
---
apiVersion: v1
kind: Service
metadata:
  name: meteor
  namespace: meteor-vanilla
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteor1
  namespace: meteor-vanilla
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
---
apiVersion: v1
kind: Service
metadata:
  name: meteor2
  namespace: meteor-vanilla
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor
