FROM uws/base-2309

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="230925"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh python3 ansible python3-libcloud ansible-lint \
	python3-boto python3-boto3

USER uws:uws
WORKDIR /home/uws

ENV USER uws
ENV HOME /home/uws

RUN mkdir -vp -m 0750 /home/uws/.ansible

RUN ansible --version \
	&& rm -rf /home/uws/.ansible/tmp

RUN mkdir -vp -m 0750 /home/uws/.ssh /home/uws/asb

WORKDIR /home/uws/asb
ENTRYPOINT /bin/bash -l
