---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-self
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
spec:
  isCA: true
  commonName: ca.uws.talkingpts.org
  secretName: ca-certificate
  issuerRef:
    name: ca-self
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: uwsca
spec:
  ca:
    secretName: ca-certificate
