FROM uws/python-2305

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="230818"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh python3-pytest python3-pytest-cov

RUN install -v -d -o uws -g uws -m 0750 /opt/uws \
	/srv/home/uwscli /srv/home/uwscli/bin /srv/home/uwscli/etc

USER uws:uws
WORKDIR /home/uws

ENV USER uws
ENV HOME /home/uws

RUN /usr/bin/python3 -m venv /opt/uws/venv
RUN /opt/uws/venv/bin/python3 -m pip install -U pip

COPY --chown=uws:uws ./build/requirements.txt /srv/home/uwscli/etc/requirements.txt
RUN /opt/uws/venv/bin/python3 -m pip install -U -r /srv/home/uwscli/etc/requirements.txt

RUN mkdir -vp ~/tmp

RUN echo 'export PATH=/srv/home/uwscli/bin:${PATH}' >>~/.profile
