FROM uws/python-2211

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="221117"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh shellcheck python3-pytest python3-pytest-cov

RUN install -v -d -o uws -g uws -m 0750 /srv/home/uwscli \
	/srv/home/uwscli/bin /srv/home/uwscli/etc

USER uws:uws
WORKDIR /home/uws

ENV USER uws
ENV HOME /home/uws

RUN mkdir -vp ~/tmp

RUN echo 'export PATH=/srv/home/uwscli/bin:${PATH}' >>~/.profile
