---
- name: RStudio apt install deps
  become: true
  ansible.builtin.apt:
    pkg:
      - gnupg
      - git
  tags:
    - apt
    - rstudio-apt

# https://cran.rstudio.com/bin/linux/debian/
- name: RStudio apt key
  become: true
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: "0x95c0faf38db3ccad0c080a7bdc78b2ddeabc47b7"
  tags:
    - apt
    - rstudio-apt

- name: RStudio apt repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb http://cloud.r-project.org/bin/linux/debian bookworm-cran40/
    state: present
    filename: rstudio
  tags:
    - apt
    - rstudio-apt

- name: RStudio apt update
  become: true
  ansible.builtin.apt:
    update_cache: true
  tags:
    - apt
    - rstudio-apt

- name: RStudio apt remove
  become: true
  ansible.builtin.apt:
    state: absent
    autoremove: true
    purge: true
    pkg:
      - gdebi-core
      - dpkg-sig
  tags:
    - apt
    - rstudio-apt

- name: RStudio apt install
  become: true
  ansible.builtin.apt:
    pkg:
      - r-base
      - xz-utils
      - r-cran-devtools
  tags:
    - apt
    - rstudio-apt
