#
# rstudio project users/groups
#
- name: project users group
  become: yes
  group:
    name: ruser
    state: present
    gid: "{{ rstudio_project_user_gid }}"
  tags:
    - rstudio-project

- name: project admin users group
  become: yes
  user:
    name: "{{ item }}"
    append: yes
    groups: ruser
  loop: "{{ rstudio_user | list }}"
  tags:
    - rstudio-project

- name: project group
  become: yes
  group:
    name: "{{ item }}"
    state: present
    gid: "{{ rstudio_project[item].gid }}"
  loop: "{{ rstudio_project | list }}"
  tags:
    - rstudio-project

- name: project admin users
  become: yes
  user:
    name: "{{ item.0 }}"
    append: yes
    groups: "{{ item.1 }}"
  loop: "{{ rstudio_user | list | product(rstudio_project | list) | list }}"
  tags:
    - rstudio-project

- name: projects basedir
  become: yes
  file:
    state: directory
    path: "{{ uws_users_homedir }}/project"
    owner: root
    group: root
    mode: '0755'
  tags:
    - rstudio-project

- name: project dir
  become: yes
  file:
    state: directory
    path: "{{ uws_users_homedir }}/project/{{ item }}"
    owner: root
    group: "{{ item }}"
    mode: '2770'
  loop: "{{ rstudio_project | list }}"
  tags:
    - rstudio-project

- name: project users base homedir
  become: yes
  file:
    state: directory
    path: "{{ uws_users_homedir }}/user"
    owner: root
    group: root
    mode: '0755'
  tags:
    - rstudio-project

- name: project user
  become: yes
  user:
    state: present
    name: "{{ item }}"
    uid: "{{ rstudio_project_user[item].uid }}"
    append: no
    comment: "{{ item }}"
    create_home: yes
    group: ruser
    groups: "{{ rstudio_project_user[item].groups }}"
    home: "{{ uws_users_homedir }}/user/{{ item }}"
    shell: /bin/bash
    expires: "{{ rstudio_user_expire }}"
  loop: "{{ rstudio_project_user | list }}"
  tags:
    - rstudio-project

- name: project user homedir
  become: yes
  file:
    state: directory
    path: "{{ uws_users_homedir }}/user/{{ item }}"
    owner: "{{ item }}"
    group: ruser
    mode: '0750'
  loop: "{{ rstudio_project_user | list }}"
  tags:
    - rstudio-project
