#
# rstudio project users/groups
#
- name: project users group
  become: yes
  group:
    name: ruser
    state: present
    gid: "{{ rstudio_project_user_gid }}"
  tags:
    - rstudio-project

- name: project group
  become: yes
  group:
    name: "{{ item }}"
    state: present
    gid: "{{ rstudio_project[item].gid }}"
  loop: "{{ rstudio_project | list }}"
  tags:
    - rstudio-project

- name: project users base homedir
  become: yes
  file:
    state: directory
    path: "{{ uws_users_homedir }}/user"
    owner: root
    group: root
    mode: '0755'
  tags:
    - rstudio-project

- name: project user
  become: yes
  user:
    state: present
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    append: no
    comment: "{{ item.name }}"
    create_home: yes
    group: ruser
    home: "{{ uws_users_homedir }}/user/{{ item.name }}"
    shell: /bin/bash
    expires: "{{ rstudio_user_expire }}"
  loop: "{{ rstudio_project_user | dict2items(key_name='name', value_name='uid') }}"
  tags:
    - rstudio-project

- name: project user homedir
  become: yes
  file:
    state: directory
    path: "{{ uws_users_homedir }}/user/{{ item.name }}"
    owner: "{{ item.name }}"
    group: ruser
    mode: '0750'
  loop: "{{ rstudio_project_user | dict2items(key_name='name', value_name='uid') }}"
  tags:
    - rstudio-project
