---
- name: apt install deps
  become: yes
  apt:
    pkg:
      - gnupg
  tags:
    - apt
    - rstudio-apt

# https://cran.rstudio.com/bin/linux/debian/
- name: apt key
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E19F5F87128899B192B1A2C2AD5F960A256A04AF
  tags:
    - apt
    - rstudio-apt

- name: apt repo
  become: yes
  apt_repository:
    repo: deb http://cloud.r-project.org/bin/linux/debian bullseye-cran40/
    state: present
    filename: rstudio
  tags:
    - apt
    - rstudio-apt

- name: apt update
  become: yes
  apt:
    update_cache: yes
  tags:
    - apt
    - rstudio-apt

- name: apt remove
  become: yes
  apt:
    state: absent
    autoremove: yes
    purge: yes
    pkg:
      - gdebi-core
      - dpkg-sig
  tags:
    - apt
    - rstudio-apt

- name: apt install
  become: yes
  apt:
    pkg:
      - r-base
      - xz-utils
  tags:
    - apt
    - rstudio-apt

- name: server install
  become: yes
  apt:
    deb: "{{ rstudio_repo }}/{{ rstudio_server_version }}"
  tags:
    - apt
    - rstudio-apt

- name: vm info
  delegate_to: localhost
  ec2_instance_info:
    filters:
      "tag:Name": "{{ inventory_hostname }}"
      availability-zone: "{{ aws_zone }}"
      instance-state-name: running
  register: rstudio_vm

- name: homefs vol
  delegate_to: localhost
  ec2_vol:
    - name: "{{ inventory_hostname }}-homefs"
      zone: "{{ aws_zone }}"
      instance: "{{ rstudio_vm.instances.0.instance_id }}"
      encrypted: yes
      volume_size: 100
      volume_type: gp2
      device_name: /dev/sdf
      delete_on_termination: no

- name: make homefs
  become: yes
  filesystem:
    dev: /dev/sdf
    fstype: ext4
    opts: -L rstudio-homefs

- name: mount homefs
  become: yes
  mount:
    path: /srv/home
    src: LABEL=rstudio-homefs
    fstype: ext4
    state: mounted
