---
- name: apt install deps
  become: yes
  apt:
    pkg:
      - gnupg
  tags:
    - apt
    - rstudio-apt

# https://cran.rstudio.com/bin/linux/debian/
- name: apt key
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E19F5F87128899B192B1A2C2AD5F960A256A04AF
  tags:
    - apt
    - rstudio-apt

- name: apt repo
  become: yes
  apt_repository:
    repo: deb http://cloud.r-project.org/bin/linux/debian bullseye-cran40/
    state: present
    filename: rstudio
  tags:
    - apt
    - rstudio-apt

- name: apt update
  become: yes
  apt:
    update_cache: yes
  tags:
    - apt
    - rstudio-apt

- name: apt remove
  become: yes
  apt:
    state: absent
    autoremove: yes
    purge: yes
    pkg:
      - gdebi-core
      - dpkg-sig
  tags:
    - apt
    - rstudio-apt

- name: apt install
  become: yes
  apt:
    pkg:
      - r-base
      - xz-utils
  tags:
    - apt
    - rstudio-apt
#
# rstudio server
#
- name: server install
  become: yes
  apt:
    deb: "{{ rstudio_repo }}/{{ rstudio_server_version }}"
  tags:
    - apt
    - rstudio-apt

- name: vm info
  delegate_to: localhost
  ec2_instance_info:
    filters:
      "tag:Name": "{{ inventory_hostname }}"
      availability-zone: "{{ aws_zone }}"
      instance-state-name: running
  register: rstudio_vm
  tags:
    - homefs
#
# homefs
#
- name: homefs vol
  delegate_to: localhost
  ec2_vol:
    name: "{{ inventory_hostname }}-homefs"
    zone: "{{ aws_zone }}"
    instance: "{{ rstudio_vm.instances.0.instance_id }}"
    encrypted: yes
    volume_size: 100
    volume_type: gp2
    device_name: /dev/sdf
    delete_on_termination: no
  tags:
    - homefs

- name: make homefs
  become: yes
  filesystem:
    dev: /dev/sdf
    fstype: ext4
    opts: -L rstudio-homefs
  tags:
    - homefs

- name: mount homefs
  become: yes
  mount:
    path: "{{ uws_users_homedir }}"
    src: LABEL=rstudio-homefs
    fstype: ext4
    state: mounted
  tags:
    - homefs
#
# rstudio users/groups
#
- name: user's group
  become: yes
  group:
    name: rstudio
    state: present
    gid: 3000
  tags:
    - users

- name: user
  become: yes
  user:
    state: present
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    append: no
    comment: "{{ item.name }}"
    create_home: yes
    group: rstudio
    home: "{{ uws_users_homedir }}/{{ item.name }}"
    shell: /bin/bash
    expires: "{{ rstudio_user_expire }}"
  loop: "{{ rstudio_user | dict2items(key_name='name', value_name='uid') }}"
  tags:
    - users

- name: user home dir
  become: yes
  file:
    state: directory
    path: "{{ uws_users_homedir }}/{{ item.name }}"
    owner: "{{ item.name }}"
    group: rstudio
    mode: '0750'
  loop: "{{ rstudio_user | dict2items(key_name='name', value_name='uid') }}"
  tags:
    - users
#
# site.html
#
- name: site.html
  become: yes
  template:
    src: rstudio/site.html
    dest: /var/www/html/site.html
    mode: '0644'
    owner: root
    group: root
  tags:
    - nginx
