---
- name: server install
  become: true
  apt:
    deb: "{{ rstudio_repo }}/{{ rstudio_server_version }}"
  tags:
    - apt
    - rstudio-apt

- name: server config
  become: true
  template:
    src: rserver.conf
    dest: /etc/rstudio/rserver.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart rstudio-server
  tags:
    - rstudio

- name: systemd service config
  become: true
  lineinfile:
    path: /lib/systemd/system/rstudio-server.service
    backup: true
    state: present
    line: 'UMask=0002'
    insertafter: '^PIDFile='
  notify:
    - reload systemd
    - restart rstudio-server
  tags:
    - rstudio

# homefs

- name: vm info
  delegate_to: localhost
  ec2_instance_info:
    filters:
      "tag:Name": "{{ inventory_hostname }}"
      availability-zone: "{{ aws_zone }}"
      instance-state-name: running
  register: rstudio_vm
  tags:
    - homefs

- name: homefs vol
  delegate_to: localhost
  ec2_vol:
    name: "{{ inventory_hostname }}-homefs"
    zone: "{{ aws_zone }}"
    instance: "{{ rstudio_vm.instances.0.instance_id }}"
    encrypted: true
    volume_size: 100
    volume_type: gp2
    device_name: /dev/sdf
    delete_on_termination: false
  tags:
    - homefs

- name: make homefs
  become: true
  filesystem:
    dev: /dev/sdf
    fstype: ext4
    opts: -L rstudio-homefs
  tags:
    - homefs

- name: mount homefs
  become: true
  mount:
    path: "{{ uws_users_homedir }}"
    src: LABEL=rstudio-homefs
    fstype: ext4
    state: mounted
  tags:
    - homefs
