---
- name: project user remove
  become: true
  user:
    state: absent
    name: "{{ item }}"
    force: false
    remove: true
  loop: "{{ rstudio_project_user_remove | list }}"
  tags:
    - rstudio-project

- name: project user
  become: true
  user:
    state: present
    name: "{{ item }}"
    uid: "{{ rstudio_project_user[item].uid }}"
    append: false
    comment: "{{ item }}"
    create_home: true
    group: ruser
    groups: "{{ rstudio_project_user[item].groups }}"
    home: "{{ uws_users_homedir }}/user/{{ item }}"
    shell: /bin/bash
    expires: "{{ rstudio_user_expire }}"
  loop: "{{ rstudio_project_user | list }}"
  tags:
    - rstudio-project

- name: project user homedir
  become: true
  file:
    state: directory
    path: "{{ uws_users_homedir }}/user/{{ item }}"
    owner: "{{ item }}"
    group: ruser
    mode: '0750'
  loop: "{{ rstudio_project_user | list }}"
  tags:
    - rstudio-project

- name: project users symlink
  become: true
  file:
    state: link
    src: "{{ uws_users_homedir }}/project"
    dest: "{{ uws_users_homedir }}/user/{{ item }}/project"
    force: true
    owner: root
    group: root
  loop: "{{ rstudio_project_user | list }}"
  tags:
    - rstudio-project

- name: project users umask
  become: true
  lineinfile:
    path: "{{ uws_users_homedir }}/user/{{ item }}/.profile"
    backup: true
    state: present
    regexp: '^umask'
    line: 'umask 0002'
  loop: "{{ rstudio_project_user | list }}"
  tags:
    - rstudio-project
