---
- name: RStudio project users group
  become: true
  ansible.builtin.group:
    name: ruser
    state: present
    gid: "{{ rstudio_project_user_gid }}"
  tags:
    - rstudio-project

- name: RStudio project admin users group
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    append: true
    groups: ruser
  loop: "{{ rstudio_user | list }}"
  tags:
    - rstudio-project

- name: RStudio project group
  become: true
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    gid: "{{ rstudio_project[item].gid }}"
  loop: "{{ rstudio_project | list }}"
  tags:
    - rstudio-project

- name: RStudio project admin users
  become: true
  ansible.builtin.user:
    name: "{{ item.0 }}"
    append: true
    groups: "{{ item.1 }}"
  loop: "{{ rstudio_user | list | product(rstudio_project | list) | list }}"
  tags:
    - rstudio-project

- name: RStudio projects basedir
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ uws_users_homedir }}/project"
    owner: root
    group: root
    mode: '0755'
  tags:
    - rstudio-project

- name: RStudio project admin users symlink
  become: true
  ansible.builtin.file:
    state: link
    src: "{{ uws_users_homedir }}/project"
    dest: "{{ uws_users_homedir }}/{{ item }}/project"
    force: true
    owner: root
    group: root
  loop: "{{ rstudio_user | list }}"
  tags:
    - rstudio-project

- name: RStudio project dir
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ uws_users_homedir }}/project/{{ rstudio_project[item].name }}"
    owner: root
    group: "{{ item }}"
    mode: '2770'
  loop: "{{ rstudio_project | list }}"
  tags:
    - rstudio-project

- name: RStudio project users base homedir
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ uws_users_homedir }}/user"
    owner: root
    group: root
    mode: '0755'
  tags:
    - rstudio-project
