#
# rstudio project users/groups
#
- name: project user's group
  become: yes
  group:
    name: ruser
    state: present
    gid: "{{ rstudio_project_user_gid }}"
  tags:
    - rstudio-project

- name: project group
  become: yes
  group:
    name: "{{ item }}"
    state: present
    gid: "{{ rstudio_project[item].gid }}"
  loop: "{{ rstudio_project | list }}"
  tags:
    - rstudio-project

#~ - name: user
  #~ become: yes
  #~ user:
    #~ state: present
    #~ name: "{{ item.name }}"
    #~ uid: "{{ item.uid }}"
    #~ append: no
    #~ comment: "{{ item.name }}"
    #~ create_home: yes
    #~ group: rstudio
    #~ home: "{{ uws_users_homedir }}/{{ item.name }}"
    #~ shell: /bin/bash
    #~ expires: "{{ rstudio_user_expire }}"
  #~ loop: "{{ rstudio_user | dict2items(key_name='name', value_name='uid') }}"
  #~ tags:
    #~ - rstudio-project

#~ - name: user home dir
  #~ become: yes
  #~ file:
    #~ state: directory
    #~ path: "{{ uws_users_homedir }}/{{ item.name }}"
    #~ owner: "{{ item.name }}"
    #~ group: rstudio
    #~ mode: '0750'
  #~ loop: "{{ rstudio_user | dict2items(key_name='name', value_name='uid') }}"
  #~ tags:
    #~ - rstudio-project
