# https://github.com/haproxy-ingress/charts/blob/release-0.14/haproxy-ingress/values.yaml
---
controller:
  autoscaling:
    enabled: ${HPX_ENABLE_AUTOSCALING}
    minReplicas: ${HPX_REPLICAS}
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  defaultBackendService: ${HPX_NAMESPACE}/${HPX_DEFAULT_BACKEND}

  extraArgs:
    disable-external-name: true
    force-namespace-isolation: true
    watch-gateway: false
    watch-namespace: ${HPX_NAMESPACE}

  ingressClass: ${HPX_NAMESPACE}-hpx
  kind: Deployment

  logging:
    # error warning info debug trace
    level: warning

  logs:
    enabled: true

  metrics:
    controllerPort: 10254
    embedded: true
    enabled: true

  minAvailable: 1

  publishService:
    enabled: false

  replicaCount: ${HPX_REPLICAS}

  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    type: LoadBalancer

  serviceMonitor:
    enabled: true

  stats:
    enabled: true

defaultBackend:
  enabled: ${HPX_ENABLE_DEFAULT_BACKEND}
  minAvailable: 1
  name: default-backend
  replicaCount: 3
