# https://github.com/haproxy-ingress/charts/blob/release-0.14/haproxy-ingress/values.yaml
---
controller:
  autoscaling:
    enabled: ${HPX_ENABLE_AUTOSCALING}
    minReplicas: ${HPX_REPLICAS}
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    #~ targetMemoryUtilizationPercentage: 80

  defaultBackendService: ${HPX_DEFAULT_BACKEND}

  extraArgs:
    acme-server: true
    force-namespace-isolation: true
    ingress-class-precedence: true
    watch-namespace: ${HPX_NAMESPACE}

  ingressClass: ${HPX_NAMESPACE}hpx
  kind: Deployment

  logging:
    # error warning info debug trace
    level: warning

  logs:
    enabled: true
    resources:
      limits:
        cpu: 10m
        memory: 10Mi
      requests:
        cpu: 1m
        memory: 1Mi

  metrics:
    controllerPort: 10254
    embedded: true
    enabled: true

  minAvailable: 1

  publishService:
    enabled: false

  replicaCount: ${HPX_REPLICAS}

  resources:
    limits:
      cpu: 30m
      memory: 200Mi
    requests:
      cpu: 3m
      memory: 20Mi

  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    type: LoadBalancer

  serviceMonitor:
    enabled: true

  stats:
    enabled: true

defaultBackend:
  enabled: ${HPX_ENABLE_DEFAULT_BACKEND}
  minAvailable: 1
  name: default-backend
  replicaCount: 3
  resources:
    limits:
      cpu: 10m
      memory: 20Mi
    requests:
      cpu: 1m
      memory: 2Mi
