FROM uws/webapp-2309

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="230925"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

###RUN /root/bin/apt-install.sh ...

USER uws:uwsops
WORKDIR /home/uws

ENV USER uws
ENV HOME /home/uws

RUN install -v -d -m 0750 /opt/uws/admin

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

COPY --chown=uws:uwsops ./src /opt/uws/admin
COPY --chown=uws:uwsops ./VERSION /opt/uws/admin

RUN install -v -d -m 0750 -o uws -g uwsops /srv/home/uwscli /srv/home/uwscli/lib

USER uws:uwsops
WORKDIR /home/uws

ENV USER uws
ENV HOME /home/uws

RUN /opt/uws/venv/bin/python3 -m compileall /opt/uws/admin

USER uwsops:uwsops
WORKDIR /home/uwsops

ENV USER uwsops
ENV HOME /home/uwsops
ENV UWS_WEBAPP_WORKERS 1
ENV UWS_WEBAPP_PORT 2741

ENTRYPOINT exec /usr/local/bin/entrypoint.sh
