---
- name: kali ec2 vm teardown
  hosts: ec2vm_teardown
  gather_facts: false
  tasks:

    - name: teardown kali vm
      delegate_to: localhost
      ec2_instance_info:
        filters:
          "tag:Name": "{{ vm_tag_name or inventory_hostname }}"
      register: teardown_vm
      tags:
        - dns

    - name: teardown kali public vm dns record
      delegate_to: localhost
      route53:
        state: absent
        zone: uws.talkingpts.org
        record: "{{ kali_public_vm }}.{{ uws_domain }}"
        value: "{{ ansible_host }}"
        ttl: 600
        type: CNAME
      when: kali_public_vm
      tags:
        - dns

    - name: teardown kali vm dns record
      delegate_to: localhost
      route53:
        state: absent
        zone: uws.talkingpts.org
        record: "{{ ansible_host }}"
        value: "{{ teardown_vm.instances.0.public_dns_name or vm_public_dns_name }}"
        ttl: 600
        type: CNAME
      when: teardown_vm.instances
      tags:
        - dns

    - name: teardown kali vm stop
      delegate_to: localhost
      ec2_instance:
        state: stopped
        wait: yes
        wait_timeout: 600
        instance_ids: "{{ teardown_vm.instances.0.instance_id }}"
        termination_protection: false
      when: teardown_vm.instances

    - block:
        - name: datafs vol
          delegate_to: localhost
          ec2_vol:
            name: kali-datafs
            instance: "{{ kali_vm.instances.0.instance_id }}"
            state: absent
      when: kali_public_vm

    - name: teardown kali vm terminate
      delegate_to: localhost
      ec2_instance:
        state: absent
        wait: yes
        wait_timeout: 600
        instance_ids: "{{ teardown_vm.instances.0.instance_id }}"
      when: teardown_vm.instances
