---
- name: Kali ec2 vpc
  hosts: ec2vpc
  gather_facts: false
  tasks:

    - name: Kali net
      delegate_to: localhost
      amazon.aws.ec2_vpc_net:
        name: kali-vpc
        state: present
        tags:
          Name: kali-vpc
        cidr_block: "{{ ec2vpc_block }}"
      register: kali_net
      tags:
        - info

    - name: Kali internet gateway
      delegate_to: localhost
      amazon.aws.ec2_vpc_igw:
        state: present
        vpc_id: "{{ kali_net.vpc.id }}"
        tags:
          Name: kali-igw
      register: kali_igw

    - name: Kali subnet
      delegate_to: localhost
      amazon.aws.ec2_vpc_subnet:
        state: present
        assign_instances_ipv6: false
        map_public: true
        cidr: "{{ ec2vpc_kali }}"
        vpc_id: "{{ kali_net.vpc.id }}"
        tags:
          Name: kali-subnet
      register: kali_subnet
      tags:
        - info

    - name: Kali subnet info
      delegate_to: localhost
      ansible.builtin.debug:
        msg: "{{ kali_subnet.subnet.id }}"
      tags:
        - info

    - name: Kali subnet route table
      delegate_to: localhost
      amazon.aws.ec2_vpc_route_table:
        state: present
        vpc_id: "{{ kali_net.vpc.id }}"
        tags:
          Name: kali-subnet
        subnets:
          - "{{ kali_subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ kali_igw.gateway_id }}"

    - name: Kali security group
      delegate_to: localhost
      amazon.aws.ec2_security_group:
        name: kali-sg
        description: kali security group
        state: present
        tags:
          Name: kali-sg
        vpc_id: "{{ kali_net.vpc.id }}"
        rules:
          - proto: tcp
            ports:
              - 22
              - 80
              - 443
              - 3327
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
