---
- name: Kali ec2 vm check
  hosts: ec2vm
  gather_facts: false
  tasks:

    - name: Kali vm running
      delegate_to: localhost
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Name": "{{ inventory_hostname }}"
          instance-state-name: running
      register: kali_vm

    - name: Kali vm dns record
      delegate_to: localhost
      amazon.aws.route53:
        state: present
        overwrite: true
        zone: "{{ uws_domain }}"
        ttl: 600
        type: CNAME
        record: "{{ ansible_host }}"
        value: "{{ kali_vm.instances.0.public_dns_name }}."
      when: kali_vm.instances

    - name: Kali vm public dns record
      delegate_to: localhost
      amazon.aws.route53:
        state: present
        overwrite: true
        zone: "{{ uws_domain }}"
        ttl: 600
        type: CNAME
        record: "{{ kali_public_vm }}.{{ uws_domain }}"
        value: "{{ ansible_host }}."
      when: kali_public_vm
