FROM uws/base-2309

LABEL maintainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="230925"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh acme-tiny

ADD --chown=root:root ./utils/*.sh /usr/local/bin/
RUN chmod -v 0755 /usr/local/bin/*.sh

VOLUME /srv/acme
ENV ACME_HOME /srv/acme

RUN install -v -d -m 0750 -o uws -g uws ${ACME_HOME}

USER uws:uws
WORKDIR /home/uws

ENV USER uws
ENV HOME /home/uws

CMD exec /bin/bash -l
