#!/bin/sh
set -eu

cluster=${1:?'cluster name?'}
files=/home/uws/files
kubectl="kubectl --kubeconfig=/home/uws/.kube/eksctl/clusters/${cluster}"

${kubectl} delete -f ${files}/metrics-server.yaml

exit 0
