#!/usr/bin/env python3

import sys
import subprocess

from argparse import ArgumentParser

def main():
	parser = ArgumentParser()
	parser.add_argument('--profile', help = 'aws credentials profile')
	parser.add_argument('--region', help = 'aws region', default = 'us-west-2')
	parser.add_argument('name', help = 'cluster name')
	args = parser.parse_args()
	if args.profile is None:
		args.profile = args.name
	cmd = _createCluster(args)
	print(cmd)
	try:
		subprocess.run(cmd, shell = True, check = True)
	except Exception:
		return 1
	cmd = 'uwseks-cluster-setup %s' % args.name
	print(cmd)
	try:
		subprocess.run(cmd, shell = True, check = True)
	except Exception:
		return 2
	return 0

def _createCluster(args):
	cmd = 'eksctl create cluster --name %s' % args.name
	cmd += ' --profile %s' % args.profile
	cmd += ' --region %s' % args.region
	cmd += ' --tags uwseks=%s' % args.name
	cmd += ' --nodegroup-name %s-ng' % args.name
	cmd += ' --instance-prefix %s' % args.name
	cmd += ' --fargate'
	cmd += ' --auto-kubeconfig'
	cmd += ' --disable-pod-imds'
	cmd += ' --asg-access'
	return cmd

if __name__ == '__main__':
	sys.exit(main())
