#!/bin/sh
set -eu

cluster=${1:?'cluster name?'}
kubectl="kubectl --kubeconfig=/home/uws/.kube/eksctl/clusters/${cluster}"
helm="helm --kubeconfig /home/uws/.kube/eksctl/clusters/${cluster}"

${helm} repo add jetstack https://charts.jetstack.io
${helm} repo update

${kubectl} create namespace cert-manager

${helm} install cert-manager jetstack/cert-manager \
	--namespace cert-manager \
	--version 1.3.0 \
	--set installCRDs=true

exit 0
