#!/bin/sh
set -eu

. ~/bin/env.export

cluster=${UWS_CLUSTER}
files=~/files
secret=~/secret

. ${secret}/secret.env

# aws users auth

uwskube apply -f ${secret}/aws-auth.yaml

# cluster autoscaler
# https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html

uwseks utils associate-iam-oidc-provider --approve

uwseks create iamserviceaccount \
	--namespace=kube-system \
	--name=cluster-autoscaler \
	--override-existing-serviceaccounts \
	--attach-policy-arn=arn:aws:iam::${AWS_ACCOUNT_ID}:policy/eksClusterAutoscaler \
	--approve

sed "s#\[UWSEKS_CLUSTER]#${cluster}#" ${files}/cluster-autoscaler.yaml >/tmp/cluster-autoscaler-${cluster}.yaml

uwskube apply -f /tmp/cluster-autoscaler-${cluster}.yaml

#~ uwskube annotate serviceaccount cluster-autoscaler \
	#~ --namespace=kube-system \
	#~ eks.amazonaws.com/role-arn=arn:aws:iam::${AWS_ACCOUNT_ID}:role/eksClusterAutoscalerRole

uwskube patch deployment cluster-autoscaler --namespace=kube-system \
	-p '{"spec":{"template":{"metadata":{"annotations":{"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"}}}}}'

exit 0
