#!/bin/sh
set -eu

cluster=${1:?'cluster name?'}
files=/home/uws/files
kubectl="kubectl --kubeconfig=/home/uws/.kube/eksctl/clusters/${cluster}"

${kubectl} delete -f ${files}/k8s-dashboard.yaml
${kubectl} delete -f ${files}/k8s-dashboard-auth.yaml

exit 0
