#!/bin/sh
set -eu

. ~/bin/env.export

cluster=${UWS_CLUSTER}
kubectl="uwskube ${cluster}"
helm="helm --kubeconfig ~/.kube/eksctl/clusters/${cluster}"
files=~/files
secret=~/secret

. ${secret}/secret.env

${helm} uninstall -n kube-system alb-controller

${kubectl} delete -k \
	"github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"

eksctl delete iamserviceaccount \
	--cluster=${cluster} \
	--profile=${AWS_PROFILE} \
	--namespace=kube-system \
	--name=alb-controller \
	--wait

aws iam delete-policy \
	--policy-arn=arn:aws:iam::${AWS_ACCOUNT_ID}:policy/uwseks-${cluster}-AWSLoadBalancerControllerIAMPolicy

exit 0
