#!/bin/sh
set -u

~/k8s/gateway/teardown.sh
~/k8s/ctl/teardown.sh
~/k8s/mon/teardown.sh
~/k8s/acme/teardown.sh
~/k8s/cert-manager/teardown.sh
~/k8s/nginx-ingress/teardown.sh
~/k8s/metrics-server/teardown.sh
~/k8s/autoscaler/teardown.sh
~/k8s/csi-driver/teardown.sh

uwseks delete iamserviceaccount \
	--namespace=kube-system \
	--name=cluster-autoscaler

exit 0
