#!/usr/bin/env python3

import sys
import subprocess

from argparse import ArgumentParser

def main():
	parser = ArgumentParser()
	parser.add_argument('--profile', help = 'aws credentials profile')
	parser.add_argument('--region', help = 'aws region', default = 'us-west-2')
	parser.add_argument('-v', help = 'verbose level', default = '3')
	parser.add_argument('name', help = 'cluster name')
	args = parser.parse_args()
	if args.profile is None:
		args.profile = args.name
	cmd = _createCluster(args)
	print(cmd)
	try:
		subprocess.run(cmd, shell = True, check = True)
	except Exception:
		return 1
	return 0

def _createCluster(args):
	cmd = 'eksctl -v %s delete cluster --name %s' % (args.v, args.name)
	cmd += ' --profile %s' % args.profile
	cmd += ' --region %s' % args.region
	cmd += ' --wait'
	return cmd

if __name__ == '__main__':
	sys.exit(main())
