#!/bin/sh
set -eu

cluster=${1:?'cluster name?'}
files=/home/uws/files
kubectl="kubectl --kubeconfig=/home/uws/.kube/eksctl/clusters/${cluster}"
helm="helm --kubeconfig /home/uws/.kube/eksctl/clusters/${cluster}"

${helm} uninstall loki-grafana --namespace prometheus

exit 0
