#!/usr/bin/env python3

# Copyright (c) Jeremías Casteglione <jeremias@talkingpts.org>
# See LICENSE file.

import sys
import cluster_delete

if __name__ == '__main__':
	sys.exit(cluster_delete.main(sys.argv[1:]))
