#!/bin/sh
set -eu

cluster=${1:?'cluster name?'}
files=/home/uws/files
kubectl="kubectl --kubeconfig=/home/uws/.kube/eksctl/clusters/${cluster}"
helm="helm --kubeconfig /home/uws/.kube/eksctl/clusters/${cluster}"

. ${files}/secret.env

${kubectl} create namespace prometheus

${helm} repo add prometheus-community https://prometheus-community.github.io/helm-charts

${helm} upgrade -i prometheus prometheus-community/prometheus \
	--namespace prometheus \
	--set alertmanager.persistentVolume.storageClass="gp2",server.persistentVolume.storageClass="gp2"

exit 0
