#!/bin/sh
set -eu

export AWS_PROFILE=${AWS_PROFILE}

cluster=${1:?'cluster name?'}
kubectl="uwskube ${cluster}"
helm="helm --kubeconfig /home/uws/.kube/eksctl/clusters/${cluster}"
files=/home/uws/files
secret=/home/uws/secret

. ${secret}/secret.env

#~ aws iam create-policy \
	#~ --policy-name uwseks-${cluster}-AWSLoadBalancerControllerIAMPolicy \
	#~ --policy-document file://${files}/alb-iam-policy.json

#~ eksctl create iamserviceaccount \
	#~ --cluster=${cluster} \
	#~ --profile=${AWS_PROFILE} \
	#~ --namespace=kube-system \
	#~ --name=alb-controller \
	#~ --attach-policy-arn=arn:aws:iam::${AWS_ACCOUNT_ID}:policy/uwseks-${cluster}-AWSLoadBalancerControllerIAMPolicy \
	#~ --override-existing-serviceaccounts \
	#~ --approve

#~ ${helm} repo add eks https://aws.github.io/eks-charts
#~ ${helm} repo update

#~ ${kubectl} apply -k \
	#~ "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"

${helm} upgrade -i alb-controller eks/aws-load-balancer-controller \
	-n kube-system \
	--set clusterName=${cluster} \
	--set serviceAccount.create=false \
	--set serviceAccount.name=alb-controller

exit 0
