#!/bin/sh
set -eu

# shellcheck source=/home/uws/secret/secret.env
. ~/secret/secret.env

# aws users auth

uwskube apply -f ~/secret/aws-auth.yaml

# cluster autoscaler
# https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html

uwseks utils associate-iam-oidc-provider --approve

uwseks create iamserviceaccount \
	--namespace=kube-system \
	--name=cluster-autoscaler \
	--override-existing-serviceaccounts \
	--attach-policy-arn=arn:aws:iam::${AWS_ACCOUNT_ID}:policy/eksClusterAutoscaler \
	--approve

~/k8s/autoscaler/setup.sh
~/k8s/metrics-server/setup.sh
~/k8s/nginx-ingress/setup.sh
~/k8s/cert-manager/setup.sh
~/k8s/acme/setup.sh

~/k8s/nginx-ingress/status.sh

exit 0
