#!/bin/sh
set -eu

cluster=${1:?'cluster name?'}
files=/home/uws/files
kubectl="kubectl --kubeconfig=/home/uws/.kube/eksctl/clusters/${cluster}"

. ${files}/secret.env

# aws users auth

${kubectl} apply -f ${files}/aws-auth.yaml

# cluster autoscaler
# https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html

eksctl utils associate-iam-oidc-provider -v4 \
	--cluster=${cluster} \
	--profile=${cluster} \
	--approve

eksctl create iamserviceaccount -v4 \
	--cluster=${cluster} \
	--namespace=kube-system \
	--name=cluster-autoscaler \
	--override-existing-serviceaccounts \
	--attach-policy-arn=arn:aws:iam::${AWS_ACCOUNT_ID}:policy/eksClusterAutoscaler \
	--approve

${kubectl} apply -f ${files}/cluster-autoscaler-one-asg.yaml

#~ ${kubectl} annotate serviceaccount cluster-autoscaler \
	#~ --namespace=kube-system \
	#~ eks.amazonaws.com/role-arn=arn:aws:iam::${AWS_ACCOUNT_ID}:role/eksClusterAutoscalerRole

${kubectl} patch deployment cluster-autoscaler --namespace=kube-system \
	-p '{"spec":{"template":{"metadata":{"annotations":{"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"}}}}}'

exit 0
