#!/usr/bin/env python3

import sys
import subprocess

from argparse import ArgumentParser

def main():
	parser = ArgumentParser()
	parser.add_argument('--profile', help = 'aws credentials profile')
	parser.add_argument('--region', help = 'aws region', default = 'us-west-2')
	parser.add_argument('--zones', help = 'aws region zones', default = 'us-west-2a,us-west-2a')
	parser.add_argument('--nodes-min', help = 'min number of nodes', default = 2)
	parser.add_argument('--nodes-max', help = 'max number of nodes', default = 2)
	parser.add_argument('--instance-types', help = 'instance types', default = 't2.small')
	parser.add_argument('--no-setup', help = 'do not run cluster setup', action = 'store_true')
	parser.add_argument('--fargate', help = 'setup fargate nodes', action = 'store_true')
	parser.add_argument('-v', help = 'verbose level', default = '3')
	parser.add_argument('name', help = 'cluster name')
	args = parser.parse_args()
	if args.profile is None:
		args.profile = args.name
	cmd = _createCluster(args)
	print(cmd)
	try:
		subprocess.run(cmd, shell = True, check = True)
	except Exception:
		return 1
	if not args.no_setup:
		cmd = 'uwseks-cluster-setup %s' % args.name
		print(cmd)
		try:
			subprocess.run(cmd, shell = True, check = True)
		except Exception:
			return 2
	return 0

def _createCluster(args):
	cmd = 'eksctl -v %s create cluster --name %s' % (args.v, args.name)
	cmd += ' --profile %s' % args.profile
	cmd += ' --region %s' % args.region
	# ~ cmd += ' --zones %s' % args.zones
	cmd += ' --tags uwseks=%s' % args.name
	cmd += ' --version 1.19'
	if args.fargate:
		cmd += ' --fargate'
	else:
		cmd += ' --managed'
		cmd += ' --nodegroup-name %s-ng' % args.name
		cmd += ' --nodes-min %d' % args.nodes_min
		cmd += ' --nodes-max %d' % args.nodes_max
		# ~ cmd += ' --instance-prefix %s' % args.name
		cmd += ' --instance-types %s' % args.instance_types
		# ~ cmd += ' --disable-pod-imds'
		cmd += ' --asg-access'
	cmd += ' --auto-kubeconfig'
	return cmd

if __name__ == '__main__':
	sys.exit(main())
