---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  add-headers: "ingress-nginx/custom-headers"
  use-forwarded-headers: "true"
  http-snippet: |
    map $sent_http_content_type $expires_beta {
      default                off;
      application/javascript 1h;
      text/css               1h;
      ~image/                1h;
    }
