---
- name: apt install
  become: yes
  apt:
    pkg:
      - python3-pip
      - jupyter
      - jupyter-notebook
      - jupyter-server
      - ipython3
      - python3-ipykernel
      - python3-metakernel
      - python3-jupyterlab-server
  tags:
    - apt
    - jupyter-notebook

- name: user
  become: yes
  user:
    state: present
    name: "{{ jupyter_notebook_user.name }}"
    uid: "{{ jupyter_notebook_user.uid }}"
    append: no
    comment: "{{ jupyter_notebook_user.name }}"
    create_home: yes
    home: "{{ uws_users_homedir }}/{{ jupyter_notebook_user.name }}"
    shell: /usr/sbin/nologin
  tags:
    - jupyter-notebook

- name: user groups
  become: yes
  user:
    state: present
    name: "{{ jupyter_notebook_user.name }}"
    append: yes
    groups: rstudio
  tags:
    - jupyter-notebook

- name: user home dir
  become: yes
  file:
    state: directory
    path: "{{ uws_users_homedir }}/{{ jupyter_notebook_user.name }}"
    owner: "{{ jupyter_notebook_user.name }}"
    group: "{{ jupyter_notebook_user.name }}"
    mode: '0750'
  tags:
    - jupyter-notebook

- name: scripts
  become: yes
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: "{{ jupyter_notebook_user.name }}"
    mode: '0750'
  loop:
    - jnb-start.sh
    - jnb-stop.sh
  tags:
    - jupyter-notebook

- name: systemd config
  become: yes
  copy:
    src: "systemd/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - jupyter-notebook.service
  tags:
    - jupyter-notebook

- name: service enable
  become: yes
  service:
    name: jupyter-notebook
    enabled: yes
  tags:
    - jupyter-notebook

- name: service started
  become: yes
  service:
    name: jupyter-notebook
    state: started
  tags:
    - jupyter-notebook
