FROM uws/eks

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="210930"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

COPY ./utils /home/uwsrun/bin
RUN install -v -m 0755 /home/uwsrun/bin/uwseks* /usr/local/bin/ \
	&& rm -vf /usr/local/bin/uwseks-cluster* \
	&& rm -rf /home/uwsrun/bin

USER uwsrun:uwsrun
WORKDIR /home/uwsrun

ENV USER uwsrun
ENV HOME /home/uwsrun
