FROM uws/eks-124-2305

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="230523"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh less shellcheck
RUN /root/bin/apt-install.sh python3 python3-coverage libjs-jquery \
	libjs-jquery-throttle-debounce libjs-jquery-tablesorter \
	libjs-jquery-isonscreen

USER uws:uws
WORKDIR /home/uws

ENV USER uws
ENV HOME /home/uws
