FROM uws/k8s-122-2203

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="220615"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

# vim is needed for uwskube edit
RUN /root/bin/apt-install.sh less git vim-tiny

USER ${UWS_UID}:${UWS_GID}
WORKDIR /home/uws

ENV USER uws
ENV HOME /home/uws

ENV EKS_VERSION 0.101.0
ENV EKS_URL https://github.com/weaveworks/eksctl/releases/download/v${EKS_VERSION}

# https://github.com/weaveworks/eksctl/tags

RUN wget ${EKS_URL}/eksctl_Linux_amd64.tar.gz \
	&& wget ${EKS_URL}/eksctl_checksums.txt \
	&& sha256sum --ignore-missing -c eksctl_checksums.txt \
	&& tar -C /tmp -xvzf eksctl_Linux_amd64.tar.gz \
	&& install -v -m 0755 /tmp/eksctl /usr/local/bin \
	&& rm -vf eksctl_*.* /tmp/eksctl

ENV HELM_VERSION 3.9.0

# https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
# https://github.com/helm/helm/tags

RUN wget -O helm.tgz https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz \
	&& tar -vxzf helm.tgz \
	&& install -v -m 0755 linux-amd64/helm /usr/local/bin/helm.real \
	&& rm -rvf helm.tgz linux-amd64 \
	&& helm.real version

COPY --chown=uws:uws ./helm-wrapper.sh /home/uws/helm-wrapper.sh
RUN install -v -m 0755 helm-wrapper.sh /usr/local/bin/helm \
	&& rm -vf helm-wrapper.sh

RUN install -v -d -m 0750 /home/uws/.kube/eksctl/clusters \
	&& install -v -d -m 0750 /home/uws/.kube/cache \
	&& install -v -d -m 0750 /home/uws/.aws \
	&& install -v -d -m 0750 /home/uws/bin \
	&& install -v -d -m 0750 /home/uws/k8s \
	&& install -v -d -m 0750 /home/uws/pod \
	&& install -v -d -m 0750 /home/uws/cluster \
	&& install -v -d -m 0750 /home/uws/secret \
	&& install -v -d -m 0750 /home/uws/tmp

ENV AWS_PROFILE uwsdev
ENV AWS_REGION us-west-2
ENV UWS_CLUSTER uwsdev

RUN printf 'export PS1="${AWS_PROFILE}@\H:\W\$ "\n' >>.profile

CMD exec /usr/local/bin/uws-login.sh
