---
- name: Jupyter apt install
  become: true
  ansible.builtin.apt:
    pkg:
      - python3-pip
      - jupyter
      - jupyter-notebook
      - jupyter-server
      - ipython3
      - python3-ipykernel
      - python3-metakernel
      - python3-jupyterlab-server
  tags:
    - apt
    - jupyter-notebook

- name: Jupyter user
  become: true
  ansible.builtin.user:
    state: present
    name: "{{ jupyter_notebook_user.name }}"
    uid: "{{ jupyter_notebook_user.uid }}"
    append: false
    comment: "{{ jupyter_notebook_user.name }}"
    create_home: true
    home: "{{ uws_users_homedir }}/{{ jupyter_notebook_user.name }}"
    shell: /usr/sbin/nologin
  tags:
    - jupyter-notebook

- name: Jupyter user groups
  become: true
  ansible.builtin.user:
    state: present
    name: "{{ jupyter_notebook_user.name }}"
    append: true
    groups: rstudio,ruser
  tags:
    - jupyter-notebook

- name: Jupyter rstudio project groups
  become: true
  ansible.builtin.user:
    state: present
    name: "{{ jupyter_notebook_user.name }}"
    append: true
    groups: "{{ item }}"
  loop: "{{ rstudio_project | list }}"
  tags:
    - jupyter-notebook
    - rstudio-project

- name: Jupyter user home dir
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ uws_users_homedir }}/{{ jupyter_notebook_user.name }}"
    owner: "{{ jupyter_notebook_user.name }}"
    group: "{{ jupyter_notebook_user.name }}"
    mode: '0750'
  tags:
    - jupyter-notebook

- name: Jupyter scripts
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: "{{ jupyter_notebook_user.name }}"
    group: root
    mode: '0550'
  loop:
    - jnb-start.sh
    - jnb-stop.sh
  tags:
    - jupyter-notebook

- name: Jupyter systemd config
  become: true
  ansible.builtin.copy:
    src: "systemd/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - jupyter-notebook.service
  tags:
    - jupyter-notebook

- name: Jupyter service enable
  become: true
  ansible.builtin.service:
    name: jupyter-notebook
    enabled: true
  tags:
    - jupyter-notebook

- name: Jupyter service started
  become: true
  ansible.builtin.service:
    name: jupyter-notebook
    state: started
  tags:
    - jupyter-notebook
