---
vm_type: t3a.small

# debian-11-amd64-20211011-792
debian_ami: ami-0a04b49ce7d910659

rstudio_repo: https://download2.rstudio.org/server/bionic/amd64
rstudio_server_version: rstudio-server-2021.09.0-351-amd64.deb

iptables_nginx_enable: yes
