---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: eks-nodegroup-upgrade
  namespace: ctl
spec:
  # m h dom mon dow
  schedule: "9 5 * * 1-4"
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: eksctl-nodegroup-upgrade
              image: 789470191893.dkr.ecr.us-east-1.amazonaws.com/uws:ctl-eks-${CTL_VERSION}
              imagePullPolicy: IfNotPresent
              command:
                - uwseks-nodegroup-upgrade
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 3000
                runAsGroup: 3000
              envFrom:
                - configMapRef:
                    name: cluster-env
              volumeMounts:
                - name: aws-auth
                  mountPath: "/home/uwsrun/.aws"
                  readOnly: true
          volumes:
            - name: aws-auth
              secret:
                secretName: aws-auth
