version: '3.6'

networks:
  default:
    driver: bridge

services:
  cluster:
    image: uws/munin-node-2305
    container_name: uws-munin-node-cluster-service
    volumes:
      - ./prod/cluster:/srv/etc/munin-node:ro
      - /srv/uws/deploy/eks/env:/uws/etc/cluster:ro
      - /srv/uws/deploy/secret/ca/uws/ops/etc:/uws/etc/ca/ops:ro
      - /srv/uws/deploy/secret/ca/uws/ops/210823/client:/uws/etc/ca/client:ro
    restart: on-failure
    ports:
      - 4900:4949
    networks:
      - default

  app:
    image: uws/munin-node-2305
    container_name: uws-munin-node-app-service
    volumes:
      - ./prod/app:/srv/etc/munin-node:ro
      - /srv/etc/sec/production:/srv/etc/sec:ro
      - /srv/uwsbot/stats/production:/uws/var/uwsbot/stats:ro
    restart: on-failure
    ports:
      - 4950:4949
    networks:
      - default

  www:
    image: uws/munin-node-2305
    container_name: uws-munin-node-www-service
    volumes:
      - ./prod/www:/srv/etc/munin-node:ro
    restart: on-failure
    ports:
      - 4951:4949
    networks:
      - default

  staging-app:
    image: uws/munin-node-2305
    container_name: uws-munin-node-staging-app-service
    volumes:
      - ./staging/app:/srv/etc/munin-node:ro
      - /srv/etc/sec/staging:/srv/etc/sec:ro
      - /srv/uwsbot/stats/staging:/uws/var/uwsbot/stats:ro
    restart: on-failure
    ports:
      - 4952:4949
    networks:
      - default

  crowd:
    image: uws/munin-node-2305
    container_name: uws-munin-node-crowd-service
    volumes:
      - ./prod/crowd:/srv/etc/munin-node:ro
    restart: on-failure
    ports:
      - 4953:4949
    networks:
      - default

  api:
    image: uws/munin-node-2305
    container_name: uws-munin-node-api-service
    volumes:
      - ./prod/api:/srv/etc/munin-node:ro
    restart: on-failure
    ports:
      - 4954:4949
    networks:
      - default
