version: '3.6'

networks:
  default:
    driver: bridge

services:
  app:
    image: uws/munin-node
    container_name: uws-munin-node-app-service
    volumes:
      - ./prod/app:/srv/etc/munin-node:ro
      - /srv/etc/sec/production:/srv/etc/sec:ro
      - /srv/uwsbot/stats/production:/uws/var/uwsbot/stats:ro
      - /srv/heroku/stats/production:/uws/var/api/stats/production:ro
    restart: on-failure
    ports:
      - 4950:4949
    networks:
      - default

  www:
    image: uws/munin-node
    container_name: uws-munin-node-www-service
    volumes:
      - ./prod/www:/srv/etc/munin-node:ro
    restart: on-failure
    ports:
      - 4951:4949
    networks:
      - default

  staging-app:
    image: uws/munin-node
    container_name: uws-munin-node-staging-app-service
    volumes:
      - ./staging/app:/srv/etc/munin-node:ro
      - /srv/etc/sec/staging:/srv/etc/sec:ro
      - /srv/uwsbot/stats/staging:/uws/var/uwsbot/stats:ro
      - /srv/heroku/stats/staging:/uws/var/api/stats/staging:ro
    restart: on-failure
    ports:
      - 4952:4949
    networks:
      - default

  crowd:
    image: uws/munin-node
    container_name: uws-munin-node-crowd-service
    volumes:
      - ./prod/crowd:/srv/etc/munin-node:ro
    restart: on-failure
    ports:
      - 4953:4949
    networks:
      - default
