#---
#apiVersion: autoscaling/v2beta2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: meteor-beta-hpa
#  namespace: meteor-beta
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: meteor-beta
#  minReplicas: 10
#  maxReplicas: 100
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 75
---
apiVersion: v1
kind: Service
metadata:
  name: meteor-beta-service
  namespace: meteor-beta
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: meteor-beta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteor-beta
  namespace: meteor-beta
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: meteor-beta
  replicas: 30
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meteor-beta
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - image: 789470191893.dkr.ecr.${AWS_REGION}.amazonaws.com/uws:meteor-beta-${METEOR_APP}
          imagePullPolicy: IfNotPresent
          name: meteor-beta
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 3000
            runAsGroup: 3000
          volumeMounts:
            - name: appenv
              mountPath: "/run/meteor"
              readOnly: true
          env:
            - name: PORT
              value: "3000"
            - name: DISABLE_JOBS
              value: "TRUE"
          resources:
            requests:
              cpu: 200m
              memory: 800Mi
            limits:
              cpu: 200m
              memory: 800Mi
          readinessProbe:
            exec:
              command:
                - node
                - --version
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: appenv
          secret:
            secretName: meteor-beta-env
