---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: munin-web
  namespace: mon
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: munin-web
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: munin-web
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - image: 789470191893.dkr.ecr.us-east-1.amazonaws.com/uws:munin-web
          imagePullPolicy: IfNotPresent
          name: munin-web
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: appenv
              mountPath: "/run/meteor"
              readOnly: true
            - name: app-tmpdir
              mountPath: "/opt/app/bundle/tmp"
            - name: tmpdir
              mountPath: "/tmp"
          resources:
            requests:
              memory: 300Mi
            limits:
              memory: 300Mi
          readinessProbe:
            exec:
              command:
                - cat
                - /etc/munin/munin.conf
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 1
      volumes:
        - name: appenv
          secret:
            secretName: meteor-app-env
        - name: app-tmpdir
          emptyDir: {}
        - name: tmpdir
          emptyDir: {}
