---
apiVersion: v1
kind: Service
metadata:
  name: munin-web
  labels:
    app.kubernetes.io/name: munin-web
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app.kubernetes.io/name: munin-web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: munin-web
  namespace: mon
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: munin-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: munin-web
    spec:
      containers:
        - image: 789470191893.dkr.ecr.us-east-1.amazonaws.com/uws:munin-web-${VERSION}
          imagePullPolicy: IfNotPresent
          name: munin-web
          ports:
            - containerPort: 80
              name: web
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: db
              mountPath: "/var/lib/munin"
              readOnly: true
            - name: cache
              mountPath: "/var/cache/munin/www"
              readOnly: true
            - name: cgi-tmp
              mountPath: "/var/lib/munin/cgi-tmp"
          resources:
            requests:
              memory: 300Mi
            limits:
              memory: 300Mi
          readinessProbe:
            exec:
              command:
                - cat
                - /etc/munin/apache24.conf
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 1
      volumes:
        - name: cgi-tmp
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 3Gi
    - metadata:
        name: cache
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
