FROM uws/crond-2211

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="230201"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh apt-transport-https gnupg

# https://github.com/heroku/cli/blob/master/install-ubuntu.sh
RUN echo 'deb https://cli-assets.heroku.com/apt ./' >/etc/apt/sources.list.d/heroku.list \
	&& wget -O heroku.key https://cli-assets.heroku.com/apt/release.key \
	&& apt-key add heroku.key \
	&& rm -vf heroku.key \
	&& /root/bin/apt-install.sh heroku

RUN /root/bin/apt-install.sh fetchmail

# /usr/lib/apt/apt.systemd.daily: 320: cannot create /var/lib/apt//daily_lock: Read-only file system
RUN rm -vf /etc/cron.daily/apt-compat /etc/cron.daily/dpkg /etc/cron.daily/logrotate

COPY ./files/etc/cron.d/uws /etc/cron.d/uws

USER uws:uws
WORKDIR /home/uws

ENV USER uws
ENV HOME /home/uws

RUN install -v -d -m 0750 -o uws -g uws ~/.cache \
	&& install -v -d -m 0777 -o uws -g uws ~/.cache/heroku \
	&& install -v -d -m 0777 -o uws -g uws ~/.local
RUN heroku version

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

ENTRYPOINT exec /usr/local/bin/entrypoint.sh
