#!/bin/sh
set -eu

mkdir -vp /srv/run
chown -v root:root /srv/run
chmod -v 0755 /srv/run /uws/bin /srv/etc

mkdir -vp /srv/uws
chown -v uws:uws /srv/uws
chmod -v 0750 /srv/uws

chmod -v 0750 ~admin
chmod -v 0750 ~uws
chmod -v 0750 ~uwsrun

systemctl daemon-reload

if test -s /etc/doas.conf; then
	chmod -v 0640 /etc/doas.conf
	chown -v root:root /etc/doas.conf
fi

exit 0
