#!/bin/sh
set -eu

mkdir -vp /srv/run
chown -v root:root /srv/run
chmod -v 0755 /srv/run /uws/bin /srv/etc

mkdir -vp /srv/uws
chown -v uws:uws /srv/uws
chmod -v 0750 /srv/uws

chmod -v 0750 ~admin
chmod -v 0750 ~uws
chmod -v 0750 ~uwsrun

systemctl daemon-reload

sudoers=/etc/sudoers.d/99-uws
if test -s ${sudoers}; then
	chmod -v 0755 /etc/sudoers.d
	chmod -v 0640 ${sudoers}
	chown -v root:root ${sudoers}
fi

install -v -d -m 0755 -o root -g root /srv/etc
install -v -d -m 0750 -o root -g root /srv/etc/sec
install -v -d -m 0750 -o root -g root /srv/etc/sec/production
install -v -d -m 0750 -o root -g root /srv/etc/sec/staging

exit 0
