#!/bin/sh
set -eu

# sudoers

sudoers=/etc/sudoers.d/99-uwscli
if test -s ${sudoers}; then
	chmod -v 0640 ${sudoers}
	chown -v root:root ${sudoers}
fi

# queue run dir

install -v -d -o uws -g uwscli -m 0750 /run/uwscli
install -v -d -o uws -g uwscli -m 0770 /run/uwscli/nq

# utils access

chmod -v 0750 ~uwscli
chown -v uwscli:uwscli ~uwscli

chmod -v 0750 ~uwscli/etc
chown -vR root:uwscli ~uwscli/etc

chmod -v 0550 ~uwscli/bin/*
chmod -v 0750 ~uwscli/bin
chown -vR root:uwscli ~uwscli/bin

chmod -v 0750 ~uwscli/lib
chown -vR root:uwscli ~uwscli/lib

# admin utils

chown -v root:uws ~uwscli/bin/app-deploy
chown -v root:uws ~uwscli/bin/app-rollin
chown -v root:uws ~uwscli/bin/app-scale

# internal utils

chown -v uwscli:root ~uwscli/bin/app-autobuild

# python compile

rm -vrf ~uwscli/lib/__pycache__
python3 -m compileall ~uwscli/lib
chown -vR root:uwscli ~uwscli/lib/__pycache__

# users profile

chmod -v 0750 ~antonio
install -v -C -m 0644 ~uwscli/etc/user.bash_profile ~antonio/.bash_profile

chmod -v 0750 ~aram
install -v -C -m 0644 ~uwscli/etc/user.bash_profile ~aram/.bash_profile

chmod -v 0750 ~gabriel
install -v -C -m 0644 ~uwscli/etc/user.bash_profile ~gabriel/.bash_profile

chmod -v 0750 ~guillermo
install -v -C -m 0644 ~uwscli/etc/user.bash_profile ~guillermo/.bash_profile

chmod -v 0750 ~jeremias
install -v -C -m 0644 ~uwscli/etc/user.bash_profile ~jeremias/.bash_profile

chmod -v 0750 ~nelson
install -v -C -m 0644 ~uwscli/etc/user.bash_profile ~nelson/.bash_profile

chmod -v 0750 ~ramiro
install -v -C -m 0644 ~uwscli/etc/user.bash_profile ~ramiro/.bash_profile

# install crontab

crontab -u uwscli ~uwscli/etc/crontab.in

# devel htmlcov

mkdir -vp -m 0750 /srv/www/ssl/uwscli
chown -v uwscli:www-data /srv/www/ssl/uwscli
chmod -v g+s /srv/www/ssl/uwscli

exit 0
