#!/bin/sh
set -eu
uwsrun='sudo -n -u uws -D /srv/uws/deploy'

date -R | tee /srv/uwscli/logs/test-setup.log
${uwsrun} ./cli/schroot/setup.sh test | tee -a /srv/uwscli/logs/test-setup.log
date -R | tee -a /srv/uwscli/logs/test-setup.log

if ! systemctl is-enabled uwscli-@test.service; then
	systemctl enable uwscli-@test.service
	systemctl start uwscli-@test.service
fi

export DOCKER_IMAGE='uws/cli-2203'

/uws/bin/service-restart.sh uwscli-@test \
	/etc/systemd/system/uwscli-@.service \
	/srv/uwscli/test/secret \
	/srv/uwscli/schroot/start.sh \
	/srv/uwscli/schroot/stop.sh

exit 0
