#!/bin/sh
set -eu

sudoers=/etc/sudoers.d/99-uwscli
if test -s ${sudoers}; then
	chmod -v 0640 ${sudoers}
	chown -v root:root ${sudoers}
fi

chmod -v 0750 ~uwscli
chown -v uwscli:uwscli ~uwscli

chmod -v 0750 ~uwscli/bin
chmod -v 0750 ~uwscli/bin/*
chmod -v 0640 ~uwscli/bin/uwscli.py

chown -vR root:uwscli ~uwscli/bin

chown -v root:uws ~uwscli/bin/app-deploy
chown -v root:uws ~uwscli/bin/app-rollin

rm -vrf ~uwscli/bin/__pycache__
python3 -m compileall ~uwscli/bin/uwscli.py

exit 0
