#!/bin/sh
set -eu
uwsrun='sudo -n -u uws -D /srv/uws/deploy'
logfn=/srv/uwscli/logs/test-setup.log

date -R | tee "${logfn}"
${uwsrun} ./cli/schroot/setup.sh test 2>&1 | tee -a "${logfn}"
date -R | tee -a "${logfn}"

if ! systemctl is-enabled uwscli-@test.service; then
	systemctl enable uwscli-@test.service 2>&1 | tee -a "${logfn}"
	systemctl start uwscli-@test.service 2>&1 | tee -a "${logfn}"
	exit 0
fi

export DOCKER_IMAGE='uws/cli-2211'

/uws/bin/service-restart.sh uwscli-@test \
	/etc/systemd/system/uwscli-@.service \
	/srv/uwscli/test/secret \
	/srv/uwscli/schroot/start.sh \
	/srv/uwscli/schroot/stop.sh \
	2>&1 | tee -a "${logfn}"

exit 0
