#!/bin/sh
set -eu

mkdir -vp /srv/deploy
chown -v uwsrun:uws /srv/deploy
chmod -v 0750 /srv/deploy

REPO=/srv/deploy/monbots.git
WDIR=/srv/deploy/monbots

umask 0027
uws='sudo -n -u uwsrun'

if ! test -d ${REPO}; then
	${uws} git init --bare ${REPO}
fi

chown -v root:uws /uws/git-monbots-*.sh
chmod -v 0750 /uws/git-monbots-*.sh

install -o root -g uws -m 0750 /uws/git-monbots-update.sh ${REPO}/hooks/update

if ! test -d ${WDIR}; then
	${uws} git clone ${REPO} ${WDIR}
fi

exit 0
