#!/bin/sh
set -eu

umask 0027

# systemd service
##install -v -C -o root -g root -m 0640 /srv/uws/deploy/srv/uwsapi/uwsapi-@.service \
##	/etc/systemd/system/uwsapi-@.service

# env dirs
##install -v -d -o root -g uws -m 0750 /srv/uwscli/apid
rm -vrf /srv/uwscli/apid

# helper scripts
##install -v -C -o root -g uws -m 0750 /srv/uws/deploy/srv/uwsapi/start.sh \
##	/srv/uwscli/apid/start.sh
##install -v -C -o root -g uws -m 0750 /srv/uws/deploy/srv/uwsapi/stop.sh \
##	/srv/uwscli/apid/stop.sh

exit 0
