#!/bin/sh
set -eu

CACHE_DIRS='/srv/cache/nginx/uws /srv/cache/nginx/uwstest'
mkdir -vp ${CACHE_DIRS}
chown -v www-data:www-data /srv/cache/nginx ${CACHE_DIRS}
chmod -v 0750 /srv/cache/nginx ${CACHE_DIRS}

WWW_DIRS='/srv/www/public /srv/www/ssl /srv/www/testssl'
mkdir -vp ${WWW_DIRS}
chown -v uws:www-data /srv/www ${WWW_DIRS}
chmod -v 0750 /srv/www ${WWW_DIRS}

chmod -v 0644 /var/www/html/index.html

rm -vf /etc/nginx/sites-enabled/*

install -v /etc/nginx/sites-available/jsbatch /etc/nginx/sites-enabled

mkdir -vp /srv/etc/ssl
dhparam=/srv/etc/ssl/dhparam.pem
if ! test -s ${dhparam}; then
	openssl dhparam -out ${dhparam} 4096
fi

if test -s /srv/acme/cert/jsbatch.uws.talkingpts.org.crt; then
	install -v /etc/nginx/sites-available/ssl-jsbatch /etc/nginx/sites-enabled
fi

# ops
install -v /etc/nginx/sites-available/ops /etc/nginx/sites-enabled
if test -s /srv/acme/cert/ops.uws.talkingpts.org.crt; then
	install -v /etc/nginx/sites-available/ssl-ops /etc/nginx/sites-enabled
fi

exit 0
