#!/bin/sh
set -eu
uws='sudo -u uws'

# grant uws users access

adduser uws docker
adduser uwsrun docker
adduser uwscli docker

# executable utils

chown -v root:uws /uws/docker-*.sh
chmod -v 0750 /uws/docker-*.sh

# restart docker service as iptables rules were reloaded before

if test 'Xtrue' = "X$(cat /etc/iptables.uws-reload 2>/dev/null)"; then
	echo 'i - firewall rules changed, restart docker service'
	systemctl restart docker
fi

# docker login

rm -vf /var/tmp/cloud-init/uws-setup-docker.*
tmpfn=$(mktemp /var/tmp/cloud-init/uws-setup-docker.XXXXXXXX)
${uws} aws ecr get-login --region us-east-1 | sed 's/-e none //' >${tmpfn}
chmod -v 0755 ${tmpfn}
${uws} ${tmpfn}
rm -vf ${tmpfn}

# docker pull images

REPO='789470191893.dkr.ecr.us-west-1.amazonaws.com/uws'
IMAGES='munin munin-backend munin-node'

for img in $(echo ${IMAGES}); do
	uri="${REPO}:${img}"
	${uws} docker pull ${uri}
done

exit 0
