#!/bin/sh
set -eu

DIRS='/srv/uwsbot/stats /uws/etc /uws/etc/env /uws/etc/env/bot /uws/var/uwsbot /uws/var/uwsbot/stats'
WWW_DIRS='/srv/uwsbot/release'
mkdir -vp ${DIRS} ${WWW_DIRS}
chown -v uws:uwsrun ${DIRS}
chown -v uws:www-data ${WWW_DIRS}
chmod -v 0750 ${DIRS} ${WWW_DIRS}

uws='sudo -n -u uws'

if test -s /srv/uws/deploy/Makefile; then
	oldwd=${PWD}
	cd /srv/uws/deploy
	# deploy uwsbot
	${uws} make uwsbot
	install -v -m 755 ./docker/uwsbot/build/uwsbot.bin /uws/bin/uwsbot
	install -v -m 755 ./docker/uwsbot/build/uwsbot-stats.bin /uws/bin/uwsbot-stats
	# deploy uwsbot devel setup for docker container on the MonitoringBots repo
	${uws} make uwsbot-devel
	install -v -m 644 ./docker/uwsbot/build/uwsbot-devel.tgz /srv/uwsbot/release
	install -v -m 644 ./docker/uwsbot/build/uwsbot.docs /srv/uwsbot/release/docs.txt
	cd /srv/uwsbot/release
	CK=$(sha256sum uwsbot-devel.tgz | cut -d ' ' -f 1)
	mv -vf uwsbot-devel.tgz ${CK}.tgz
	cd ${oldwd}
fi

rm -vf /uws/etc/env/bot/*
install -v -m 640 -o uws -g uwsrun /srv/uws/deploy/go/etc/env/bot/* /uws/etc/env/bot
chown -vR uws:uwsrun /uws/etc/env/bot

rm -vf /etc/munin/plugins/uwsbot_stats
ln -svf /uws/bin/uwsbot-stats /etc/munin/plugins/uwsbot_stats

# adduser uws to uwsrun group so it can access deployed monbots repo.
adduser uws uwsrun

exit 0
