#!/bin/sh
set -eu

DIRS='/srv/heroku /srv/heroku/stats'
mkdir -vp ${DIRS}
chown -v uws:uwsrun ${DIRS}
chmod -v 0750 ${DIRS}

uws='sudo -n -u uws'

if test -s /srv/uws/deploy/Makefile; then
	oldwd=${PWD}
	cd /srv/uws/deploy
	# build container
	${uws} make heroku
	${uws} make heroku-logger
	install -v -C ./docker/heroku/build/api-stats.bin /uws/bin/api-stats
	cd ${oldwd}
fi

exit 0
