#!/bin/sh
set -eu

adduser dovecot mail

mkdir -vp /srv/vmail
chmod -v 0750 /srv/vmail
chown -v mail:mail /srv/vmail

if test -s /srv/uws/deploy/secret/vmail/users; then
	install -v -C -o root -g dovecot -m 0640 /srv/uws/deploy/secret/vmail/users \
		/etc/dovecot/users
fi

postmap /etc/postfix/vmail_alias

/uws/bin/service-restart.sh dovecot /etc/dovecot/local.conf /etc/dovecot/users \
	/etc/postfix/vmail_box /etc/postfix/vmail_alias

exit 0
