#!/bin/sh
set -eu

mkdir -vp /srv/vmail
chmod -v 0750 /srv/vmail
chown -v mail:mail /srv/vmail

if test -s /srv/uws/deploy/secret/vmail/users; then
	install -v -C -o root -g root -m 0640 /srv/uws/deploy/secret/vmail/users \
		/etc/dovecot/users
fi

/uws/bin/service-restart.sh dovecot /etc/dovecot/local.conf /etc/dovecot/users

exit 0
