#!/bin/sh
set -eu

DIRS='/uws/munin /srv/munin /srv/etc/munin'
chown -v root:uws ${DIRS}
chmod -v 0750 ${DIRS}

chown -v root:uws /uws/munin/*.sh
chmod -v 0750 /uws/munin/*.sh

sudo -n -u uws -D /srv/uws/deploy make munin

if ! systemctl is-enabled uws-munin.service; then
	systemctl enable uws-munin.service
	systemctl start uws-munin
fi

/uws/bin/service-restart.sh uws-munin /uws/munin/service-start.sh /srv/etc/munin

exit 0
