#!/bin/sh
set -eu


# 231218 disabled by jrms
set +e
systemctl stop uws-munin
if systemctl is-enabled uws-munin.service; then
	systemctl disable uws-munin.service
fi
exit 0


DIRS='/uws/munin /srv/munin /srv/etc/munin'
chown -v root:uws ${DIRS}

chmod -v 0750 /srv/etc/munin
chmod -v 0751 /srv/munin
chmod -v 0751 /uws/munin

chown -v root:uws /uws/munin/*.sh
chmod -v 0750 /uws/munin/*.sh

sudo -n -u uws -D /srv/uws/deploy make munin

if ! systemctl is-enabled uws-munin.service; then
	systemctl enable uws-munin.service
	systemctl start uws-munin
fi

install -v -o root -g root -m 0640 \
	/srv/uws/deploy/secret/mongodb/meteor/app/munin-plugin.conf \
	/etc/munin/plugin-conf.d/mongodb

export DOCKER_IMAGE='uws/munin-2309'

/uws/bin/service-restart.sh uws-munin \
	/uws/munin/service-start.sh \
	/srv/etc/munin \
	/etc/munin/plugin-conf.d/mongodb \
	/srv/uws/deploy/secret/eks/files/munin

exit 0
