#!/bin/sh
set -eu

mkdir -vp /srv/run/munin-node

lastfn=/srv/run/munin-node/contrib-last.id
if ! test -s ${lastfn}; then
	echo 'NONE' >${lastfn}
fi
LAST="$(cat ${lastfn})"

CUR="$(docker image inspect -f '{{.Id}}' uws/munin-node 2>/dev/null || true)"
if test "X${CUR}" != "X${LAST}"; then
	echo 'i - munin-node install contrib plugins'
	docker run --rm --name uws-munin-node-contrib-install \
		--hostname munin-node-contrib-install.uws.local \
		-v /etc/munin/plugins:/etc/munin/plugins \
		-v /uws/munin:/mnt/munin \
		-v /srv/etc/munin-node:/srv/etc/munin-node \
		-u root --entrypoint /root/bin/contrib-install.sh uws/munin-node-2309
	echo "${CUR}" >${lastfn}
fi

pl_ena=/uws/munin/plugin-enable.sh
chmod 0750 ${pl_ena}

echo 'i - munin-node plugins enable'

${pl_ena} munin_stats
${pl_ena} munin_update

rm -vf /etc/munin/plugins/docker_multi
${pl_ena} contrib docker/docker_ docker_containers
${pl_ena} contrib docker/docker_ docker_cpu
${pl_ena} contrib docker/docker_ docker_images
${pl_ena} contrib docker/docker_ docker_memory
${pl_ena} contrib docker/docker_ docker_status
${pl_ena} contrib docker/docker_ docker_volumes

rm -vf /etc/munin/plugins/mongo*
#~ ${pl_ena} contrib mongodb/mongodb_conn mongodb_conn
#~ ${pl_ena} contrib mongodb/mongodb_docs mongodb_docs
#~ ${pl_ena} contrib mongodb/mongo_lag mongo_lag
#~ ${pl_ena} contrib mongodb/mongo_mem mongo_mem
#~ ${pl_ena} contrib mongodb/mongo_ops mongo_ops

${pl_ena} contrib dovecot/dovecot dovecot

rm -vf /etc/munin/plugins/api*
rm -vf /etc/munin/plugins/app*
rm -vf /etc/munin/plugins/uwsbot_stats

ls /etc/munin/plugins >/srv/run/uws-service-restart/munin-node.plugins

/uws/bin/service-restart.sh munin-node /etc/munin \
	/srv/run/uws-service-restart/munin-node.plugins /etc/munin/plugin-conf.d

exit 0
