#!/bin/sh
set -eu

sudo -n -u uws -D /srv/uws/deploy make munin-node

chown -vR root:uws /srv/etc/munin-node

if ! systemctl is-enabled uws-munin-node.service; then
	systemctl enable uws-munin-node.service
	systemctl start uws-munin-node
fi

/uws/bin/service-restart.sh uws-munin-node /srv/etc/munin-node

exit 0
