#!/bin/sh
set -eu

DIRS='/srv/api /srv/api/stats'
mkdir -vp ${DIRS}
chown -v uws:uws ${DIRS}
chmod -v 0750 ${DIRS}

chmod -v 0755 /uws/bin/api-logger.sh

cd /srv/uws/deploy
sudo -n -u uws make api

if ! systemctl is-enabled uws-meteor.service; then
	systemctl enable uws-meteor.service
fi

/uws/bin/service-restart.sh uws-meteor /srv/uws/deploy/srv/api

exit 0
