#!/bin/sh
set -eu

cd /srv/uws/deploy
make api

if ! systemctl is-enabled uws-meteor.service; then
	systemctl enable uws-meteor.service
fi

/uws/bin/service-restart.sh uws-meteor /srv/uws/deploy/srv/api

exit 0
