#!/bin/sh
set -eu

DIRS='/srv/api /srv/api/stats'
mkdir -vp ${DIRS}
chown -v uws:uws ${DIRS}
chmod -v 0750 ${DIRS}

chmod -v 0755 /uws/bin/api-logger.sh

chown -v uws:uwsrun /uws/bin/uwsbot-testing.sh
chmod -v 0750 /uws/bin/uwsbot-testing.sh

cd /srv/uws/deploy
sudo -n -u uws make api

install -v -m 0755 ./docker/golang/build/api-logs.bin /uws/bin/api-logs
install -v -m 0755 ./docker/golang/build/apivsbot.bin /uws/bin/apivsbot

if ! systemctl is-enabled uws-meteor.service; then
	systemctl enable uws-meteor.service
fi

/uws/bin/service-restart.sh uws-meteor /srv/uws/deploy/srv/api

exit 0
