#!/bin/sh
set -eu

mkdir -vp /srv/sftp/home
chown -v uwsrun:nogroup /srv/sftp
chmod -v 750 /srv/sftp/home
chown -v uwsrun:nogroup /srv/sftp/home
chmod -v 770 /srv/sftp/home

sudo -n -u uws -D /srv/uws/deploy make proftpd

if ! systemctl is-enabled uws-sftp.service; then
	systemctl enable uws-sftp.service
	systemctl start uws-sftp
fi

export DOCKER_IMAGE='uws/proftpd'
/uws/bin/service-restart.sh uws-sftp /srv/uws/deploy/srv/proftpd /uws/init/40-uws-sftp-service

exit 0
