#!/bin/sh
set -eu

if ! systemctl is-enabled herokud.service; then
	systemctl enable herokud.service
	systemctl start herokud
fi

export DOCKER_IMAGE='uws/herokud'
/uws/bin/service-restart.sh herokud /srv/uws/deploy/srv/herokud /uws/init/41-herokud-service

exit 0
