#!/bin/sh
set -eu

# staging worker
if ! systemctl is-enabled meteor-worker-staging.service; then
	systemctl enable meteor-worker-staging
fi

/uws/bin/service-restart.sh meteor-worker-staging /srv/uws/deploy/srv/worker

exit 0
