#!/bin/sh
set -eu

##sudo -n -u uws -D /srv/uws/deploy make ab-publish

if ! systemctl is-enabled uws-abench.service; then
	systemctl enable uws-abench.service
	systemctl start uws-abench
fi

abench_version=$(cat /srv/uws/deploy/srv/ab/VERSION.prod)
export DOCKER_IMAGE="uws/abench-${abench_version}"

install -v -d -m 0755 -o root -g uws /srv/run/webapp/prod/ab

install -v -m 0644 -o root -g uws \
	/srv/uws/deploy/secret/webapp/prod/ab.env \
	/srv/run/webapp/prod/ab.env

install -v -m 0644 -o root -g uws \
	/srv/uws/deploy/secret/webapp/prod/ab/ab_conf.py \
	/srv/run/webapp/prod/ab/ab_conf.py

install -v -d -m 1777 -o root -g root /srv/run/webapp/prod/ab/data

/uws/bin/service-restart.sh uws-abench \
	/srv/run/webapp/prod/ab.env \
	/srv/run/webapp/prod/ab \
	/srv/uws/deploy/srv/ab/VERSION.prod \
	/srv/uws/deploy/srv/ab/stop.sh \
	/srv/uws/deploy/srv/ab/start.sh

exit 0
