#!/bin/sh
set -eu

##sudo -n -u uws -D /srv/uws/deploy make ab-publish

if ! systemctl is-enabled uws-abench.service; then
	systemctl enable uws-abench.service
	systemctl start uws-abench
fi

abench_version=$(cat /srv/uws/deploy/srv/ab/VERSION.prod)
export DOCKER_IMAGE="uws/abench-${abench_version}"

/uws/bin/service-restart.sh uws-abench \
	/srv/uws/deploy/secret/webapp/prod/ab.env \
	/srv/uws/deploy/secret/webapp/prod/ab \
	/srv/uws/deploy/srv/ab/VERSION.prod \
	/srv/uws/deploy/srv/ab/stop.sh \
	/srv/uws/deploy/srv/ab/start.sh

exit 0
