.PHONY: all
all: uws/node-exporter.json

uws/node-exporter.json: Makefile
	@wget -O uws/node-exporter.json https://raw.githubusercontent.com/rfrail3/grafana-dashboards/master/prometheus/node-exporter-full.json
