---
- name: apt install
  become: true
  apt:
    pkg:
      - monit
  tags:
    - apt

- name: service enable
  become: true
  service:
    name: monit
    enabled: true
  tags:
    - monit

- name: service
  become: true
  service:
    name: monit
    state: started
  tags:
    - monit

- name: monitrc
  become: true
  template:
    src: monitrc
    dest: /etc/monit/conf.d/monitrc
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart monit
  tags:
    - monit
