---
- name: Monit apt install
  become: true
  ansible.builtin.apt:
    pkg:
      - monit
  tags:
    - apt

- name: Monit service enable
  become: true
  ansible.builtin.service:
    name: monit
    enabled: true
  tags:
    - monit

- name: Monit service
  become: true
  ansible.builtin.service:
    name: monit
    state: started
  tags:
    - monit

- name: Monit rc
  become: true
  ansible.builtin.template:
    src: monitrc
    dest: /etc/monit/conf.d/monitrc
    owner: root
    group: root
    mode: '0644'
  notify:
    - Monit restart
  tags:
    - monit
