apiVersion: 1

#deleteDatasources:
#  - name: Prometheus
#    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    orgId: 1
    uid: prom
    access: proxy
    isDefault: true
    editable: false
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
    version: 1
