FROM uws/base-2203

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="220419"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh openssh-client

COPY ./build/uwsapi.bin /usr/local/bin/uwsapi
RUN chmod -v 0550 /usr/local/bin/uwsapi \
	&& chgrp -v uwsops /usr/local/bin/uwsapi

USER uwsops:uwsops
WORKDIR /home/uwsops

ENV USER uwsops
ENV HOME /home/uwsops

ENTRYPOINT exec /usr/local/bin/uwsapi
